### ISSUE TITLE
deserialize untagged enum nested in struct?

### ISSUE THREAD

**Issue by dlaehnemann** [BurntSushi/rust-csv#100]
In a project using `csv`, we (@johanneskoester and I) have a setup similar to the StructWithEnum in the minimal code example below. While in `example1()` with the `EasyStruct` the `deserialize()` does work, `example2()` with the untagged enum panics as follows:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 27, line: 2, record: 1 }), err: DeserializeError { field: None, kind: Message("data did not match any variant of untagged enum AnEnum") } })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm not sure if I am missing some way of making this work, e.g. by providing some infos to serde how to deserialize the enum? Or if this is just plain impossible?

```
#[macro_use]
extern crate serde_derive;
extern crate csv;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct EasyStruct {
    primitive_1: u8,
    primitive_2: String
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
struct StructWithEnum {
    a_primitive: u8,
    an_enum: AnEnum
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
enum AnEnum {
    OneVersion(String),
    AnotherVersion(String)
}

fn example1() {
    let easy_struct = "\
string,primitive_1,primitive_2
string_x,42,1
string_y,42,Another
";
    let mut reader = csv::ReaderBuilder::new().has_headers(false).from_reader(easy_struct.as_bytes());
    let deserialized = reader.deserialize().skip(1); // skip header, which we can't do in ReaderBuilder when .has_headers(false)
    let unwrapped = deserialized.collect::<Result<Vec<(String, EasyStruct)>, _>>().unwrap();

    let es_1 = EasyStruct { primitive_1: 42, primitive_2: String::from("1") };
    let es_2 = EasyStruct { primitive_1: 42, primitive_2: String::from("Another") };
    assert_eq!(unwrapped, vec![
        (String::from("string_x"), es_1),
        (String::from("string_y"), es_2) ] );
}

fn example2() {
    let struct_with_enum = "\
string,a_primitive,an_enum
string_x,42,1
string_y,42,Another
";

    let mut reader = csv::ReaderBuilder::new().has_headers(false).from_reader(struct_with_enum.as_bytes());
    let deserialized = reader.deserialize().skip(1); // skip header, which we can't do in ReaderBuilder when .has_headers(false)
    let unwrapped = deserialized.collect::<Result<Vec<(String, StructWithEnum)>, _>>().unwrap();

    let swe_1 = StructWithEnum { a_primitive: 42, an_enum: AnEnum::OneVersion( String::from("1") ) };
    let swe_2 = StructWithEnum { a_primitive: 42, an_enum: AnEnum::AnotherVersion( String::from("Another") ) };
    assert_eq!(unwrapped, vec![
        (String::from("string_x"), swe_1),
        (String::from("string_y"), swe_2) ] );
}

fn main() {
    example1();
    example2();
}
```

Related to this, I'll open an issue about skipping header lines while `has_header(false)` as in the code example above.

**Comment by BurntSushi** [comment]
What is your expected output? Try removing String from each of your
variants.

**Comment by dlaehnemann** [comment]
Jep, you were right, the example was not yet minimal and drilling it down I think I have now come to the bottom of it. The following still throws the same error as above:
```
#[macro_use]
extern crate serde_derive;
extern crate csv;

use std::io;
use std::error::Error;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
enum AnEnum {
    OneVersion(String),
    AnotherVersion(String)
}

fn example1() -> Result<(), Box<Error>>{

    let ae_1 = AnEnum::OneVersion( String::from("1") );
    let ae_2 = AnEnum::AnotherVersion( String::from("Another") );

    // enum writing
    let mut wtr = csv::Writer::from_writer(io::stdout());
    
    wtr.write_record(&["an_enum"])?;
    wtr.serialize((&ae_1))?;
    wtr.serialize((&ae_2))?;
    
    wtr.flush()?;

    // enum reading
    let an_enum = "\
an_enum
1
Another
";

    let mut reader = csv::ReaderBuilder::new().from_reader(an_enum.as_bytes());
    let unwrapped = reader.deserialize().collect::<Result<Vec<AnEnum>, _>>()?;
    assert_eq!(unwrapped, vec![ ae_1, ae_2 ] );
    
    Ok(())
}

fn main() {
    if let Err(e) = example1() {
        eprintln!("Encountered Error: {}", e);
    }
}
```
Before the error is encountered, this gives the following `stdout` output:
```
an_enum
1
Another
``` 

So I think the culprit here is both of the enum variants wrap around a `String`, but the wrapping information (`OneVersion()` vs. `AnotherVersion()`) is not printed out. So for some other code reading in the earlier `csv` output, inference of which variant to use for decoding is ambiguous. So would it make sense to print out the wrapping information, as well?

**Comment by BurntSushi** [comment]
The CSV format doesn't support what you are trying to do. You need to implement your own serialize/deserialize if you want full enum support. Please consider reading the serialization docs more carefully. I believe enum suppirt is explained.

**Comment by dlaehnemann** [comment]
I have read all those parts of the docs, but what made me think that maybe it was possible is that similar to what I reported in issue #101, this worked with our previous code using `decode()` in `csv` `0.15.0` and I thought it would be great if it also could for `csv >= 1.0.0`. But I have no clue how this worked previously, as the output of the writing was the same and the ambiguity for the reading would have also been the same.

But maybe consider it a feature request for `csv` to also work on `enum`s like the one above, e.g. by serializing both variable name and variable argument whenever present and by deserializing based on them both, which should make it unambiguous. I could create a separate issue with that feature request, if you would prefer that--but can also understand if you say this is impossible or not anywhere on the list and just close this issue.

**Comment by BurntSushi** [comment]
Ya sorry, it ain't happening. I do not want to invent and maintain a secondary format on top of CSV.

The old version didn't write the variant either. I don't think this case was explicitly supported, so if it worked, you probably got lucky.
