### ISSUE TITLE
Excel-format support (AKA sep=,)

### ISSUE THREAD

**Issue by Cokemonkey11** [BurntSushi/rust-csv#103]
Hi,

In this discussion - https://www.reddit.com/r/rust/comments/6cryoi/rust_and_csv_parsing/dhx1u7l/ - `sep=,` support is mentioned, and there is a request for information about a use-case and/or other APIs.

I have a client whose only requirement is that the data I emit is convenient to open in Microsoft Excel. For such a simple program, CSV is the obvious choice of file format.

In python, this is done by initialising a csv writer/reader with `dialect='excel'` - https://docs.python.org/3/library/csv.html

I think that API is fairly fluent.

I can also see the argument for never polluting the rust-csv API wtih product-specific code.

Unfortunately, the current API makes it basically impossible to provide excel-support without closing the CSV writer and then prepending the buffer outwith rust-csv.

I think there are a few ways to resolve this:

# Writer.write_record(self, I record, bool check_colcount)

This overload would allow an author to use

`wtr.write_record(["sep=,"].iter(), false)?;`

(Currently this isn't possible because rust-csv will `error: CSV error: found record with 22 fields, but the previous record has 1 fields`)

# Writer.write_preamble(&mut self, &[u8])

A special method for writing non-CSV content like comments. Is a runtime error if called after some write_record

# Writer.flush_and_prepend(&mut self, &[u8])

A special flush method which performs a prepend with no colcount checks. Intended to be used just before dropping Writer.

# Writer::from_writer(W writer, Dialect dialect)

Similar to the python API - not much to say here apart from that it unfortunately adds product-specific code.

**Comment by BurntSushi** [comment]
Thanks for submitting this issue! Unfortunately, I'm having a really hard time reconciling at least a couple important claims you've made here.

> In python, this is done by initialising a csv writer/reader with dialect='excel'

Could you please show an example? I can't get it to emit a `sep=,` header:

```
>>> import csv
>>> import io
>>> buf = io.StringIO()
>>> wtr = csv.writer(buf, dialect='excel')
>>> wtr.writerows([['foo', 'bar', 'baz'], ['abc', 'def', 'ghi'], ['mno', 'pqr', 'stu']])
>>> buf.getvalue()
'foo,bar,baz\r\nabc,def,ghi\r\nmno,pqr,stu\r\n'
```

> Unfortunately, the current API makes it basically impossible to provide excel-support without closing the CSV writer and then prepending the buffer outwith rust-csv.

I don't think I buy this. Why can't you write your special header before creating the CSV writer? e.g.,

```rust
extern crate csv;

use std::io::{self, Write};

fn main() {
    let mut wtr = io::stdout();
    writeln!(wtr, "sep=,").unwrap();

    let mut csvwtr = csv::Writer::from_writer(wtr);
    csvwtr.serialize(("foo", "bar", "baz")).unwrap();
    csvwtr.serialize(("abc", "def", "ghi")).unwrap();
    csvwtr.serialize(("mno", "pqr", "stu")).unwrap();
    csvwtr.flush().unwrap();
}
```

> I think there are a few ways to resolve this:

Before we jump to resolutions, could we please at least specify what the behavior should be here? What is the syntax? Is it documented anywhere? Do other CSV libraries support it? Should the CSV reader be aware of it too?

**Comment by Cokemonkey11** [comment]
> I don't think I buy this. Why can't you write your special header before creating the CSV writer? e.g.,

I haven't done much tinkering with functions generic over `Write`. I've just managed to do this pretty trivially.

I wonder if this belongs in the cookbook instead of an API change.

Sorry for the overly-prescriptive first post. I agree this is more complicated than I make it out.

Frankly, I'm not super interested in this at a proposal level anymore, so happy to close, but if you'd like to think about it more and/or me to respond to your previous points, I'm happy for that too.

**Comment by BurntSushi** [comment]
I'm happy to close this as well. This kind of change can be very easily done in a backwards compatible way, so I'm content with punting on it until someone can provide more concrete details. :-)

**Comment by BurntSushi** [comment]
A cookbook example would be great!
