### ISSUE TITLE
Allow serializing in a loop

### ISSUE THREAD

**Issue by Sneagan** [BurntSushi/rust-csv#108]
I hope I didn't just miss some documentation. It seems that when I run `wtr.serialize()` while looping over a `Vec<>` of records that share a signature, only the header is written.

```
fn write_results_csv(item_array: record::Record) -> Result<(), Box<Error>> {
    let mut wtr = Writer::from_path("results.csv")?;
    for item in item_array.data {
        println!("{:?}", item);
        wtr.serialize(item)?;
    }
    wtr.flush()?;
    Ok(())
}
```

**Comment by BurntSushi** [comment]
When filling bugs, please provide a complete reproducible example that others can compile and run. Please also provide your actual output and expected output.

**Comment by BurntSushi** [comment]
@Sneagan Bug reports without sufficient detail, like the ability to reproduce the problem, are not actionable. So I'm closing this.
