### ISSUE TITLE
Deserializer does not work with `serde(default)`

### ISSUE THREAD

**Issue by RReverser** [BurntSushi/rust-csv#109]
I'm using `serde(default)` / `serde(default = "...")` to populate records with fallback values when they're not present in the input, just like with any other deserializer:

```rust
extern crate csv;
extern crate serde;

#[macro_use]
extern crate serde_derive;

#[derive(Debug, Deserialize)]
pub struct Record {
    #[serde(default)]
    x: u32,

    #[serde(default)]
    y: u32,
}

fn main() {
    let reader = csv::Reader::from_reader(b"\
x,y
0,1
,2
3,
,
5,6
" as &[u8]);

    reader.into_deserialize().for_each(|res: Result<Record, _>| {
        println!("{:?}", res);
    });
}
```

However, this doesn't work with csv crate - supposedly, even for struct fields, it returns an empty string instead of a missing field, so such records are reported as errors:

```
Ok(Record { x: 0, y: 1 })
Err(Error(Deserialize { pos: Some(Position { byte: 8, line: 3, record: 2 }), err: DeserializeError { field: Some(0), kind: ParseInt(ParseIntError { kind: Empty }) } }))
Err(Error(Deserialize { pos: Some(Position { byte: 11, line: 4, record: 3 }), err: DeserializeError { field: Some(1), kind: ParseInt(ParseIntError { kind: Empty }) } }))
Err(Error(Deserialize { pos: Some(Position { byte: 14, line: 5, record: 4 }), err: DeserializeError { field: Some(0), kind: ParseInt(ParseIntError { kind: Empty }) } }))
Ok(Record { x: 5, y: 6 })
```

**Comment by BurntSushi** [comment]
As far as I can tell, this is working as intended. Your comparison with "any other deserializer" does not seem correct, since the `x` and `y` fields *are* present in your data, they just have *empty* values in some cases. It would be like this JSON:

```json
{"x": 0, "y": 1}
{"x": null, "y": 2}
{"x": 3, "y": null}
{"x": null, "y": null}
{"x": 5, "y": 6}
```

Indeed, observe how your example code works given a more faithful port:

```rust
extern crate serde;
extern crate serde_json;

#[macro_use]
extern crate serde_derive;

#[derive(Debug, Deserialize)]
pub struct Record {
    #[serde(default)]
    x: u32,

    #[serde(default)]
    y: u32,
}

fn main() {
    let data = r#"
{"x": 0, "y": 1}
{"x": null, "y": 2}
{"x": 3, "y": null}
{"x": null, "y": null}
{"x": 5, "y": 6}
"#;
    for line in data.lines().filter(|x| !x.is_empty()) {
        let r: Result<Record, _> = serde_json::from_str(line);
        println!("{:?}", r);
    }
}
```

whose output is:

```
Ok(Record { x: 0, y: 1 })
Err(ErrorImpl { code: Message("invalid type: null, expected u32"), line: 1, column: 10 })
Err(ErrorImpl { code: Message("invalid type: null, expected u32"), line: 1, column: 18 })
Err(ErrorImpl { code: Message("invalid type: null, expected u32"), line: 1, column: 10 })
Ok(Record { x: 5, y: 6 })
```

... which exactly matches the behavior of the csv crate.

Thankfully, serde is supremely flexible, so you can actually achieve what you want, which is to presumably give default values to values that are otherwise empty or null (but still produce parse errors if they are non-empty and invalid integers):

```rust
extern crate csv;
extern crate serde;

#[macro_use]
extern crate serde_derive;

#[derive(Debug, Deserialize)]
pub struct Record {
    #[serde(deserialize_with = "default_if_empty")]
    x: u32,

    #[serde(deserialize_with = "default_if_empty")]
    y: u32,
}

fn default_if_empty<'de, D, T>(de: D) -> Result<T, D::Error>
where D: serde::Deserializer<'de>, T: serde::Deserialize<'de> + Default,
{
    use serde::Deserialize;
    Option::<T>::deserialize(de).map(|x| x.unwrap_or_else(|| T::default()))
}

fn main() {
    let reader = csv::Reader::from_reader(b"\
x,y
0,1
,2
3,
,
5,6
" as &[u8]);

    reader.into_deserialize().for_each(|res: Result<Record, _>| {
        println!("{:?}", res);
    });
}
```

output:

```
Ok(Record { x: 0, y: 1 })
Ok(Record { x: 0, y: 2 })
Ok(Record { x: 3, y: 0 })
Ok(Record { x: 0, y: 0 })
Ok(Record { x: 5, y: 6 })
```

And this method works with the JSON example above as well.

**Comment by RReverser** [comment]
> are present in your data

I'd say this is a limitation of the underlying format that doesn't allow to distinguish missing cells from empty strings, which renders `serde(default)` useless for this format.

What I'm suggesting as a fix and willing to send as a PR is to not report fields which are empty *if* deserializer expects a non-string value (which would follow similar behaviour to already implemented `Option<_>`, but would allow it to work for non-Option types as well).

**Comment by RReverser** [comment]
There is no other useful behaviour for  e.g. `empty string -> integer type` pairs anyway, so allowing it to fallback to default value if present (and keeping error otherwise) would be a non-breaking change.

**Comment by BurntSushi** [comment]
> which renders serde(default) useless for this format.

... no, it doesn't. If you added a field to your struct like this:

```rust
#[derive(Debug, Deserialize)]
pub struct Record {
    #[serde(deserialize_with = "default_if_empty")]
    x: u32,

    #[serde(deserialize_with = "default_if_empty")]
    y: u32,

    #[serde(default)]
    z: u32,
}
```

and didn't change your data, then `z` would be correctly identified as missing, and serde will fill it with a default value. This might look border-line tautological, but if you're using the same struct to deserialize multiple similar-but-not-identical CSV data files, then `serde(default)` actually might be quite useful!

> What I'm suggesting as a fix and willing to send as a PR is to not report fields which are empty if deserializer expects a non-string value (which would follow similar behaviour to already implemented `Option<_>`, but would allow it to work for non-Option types as well).

I'd rather not add special cases like this. From my perspective, the current behavior is exactly consistent with how other serde deserializers work.

(Also, it's not even clear how such a special case would be implemented, but even if you could do it, I don't think I'd want it.)

**Comment by RReverser** [comment]
> and didn't change your data, then z would be correctly identified as missing, and serde will fill it with a default value

If you mean something like

```csv
x,y
1
```

that doesn't invoke default on `y` either, instead falling with error (not that it would help with my original issue).

**Comment by BurntSushi** [comment]
No, I mean exactly what I said. Here's the full code:

```rust
extern crate csv;
extern crate serde;

#[macro_use]
extern crate serde_derive;

#[derive(Debug, Deserialize)]
pub struct Record {
    #[serde(deserialize_with = "default_if_empty")]
    x: u32,

    #[serde(deserialize_with = "default_if_empty")]
    y: u32,

    #[serde(default)]
    z: u32,
}

fn default_if_empty<'de, D, T>(de: D) -> Result<T, D::Error>
where D: serde::Deserializer<'de>, T: serde::Deserialize<'de> + Default,
{
    use serde::Deserialize;
    Option::<T>::deserialize(de).map(|x| x.unwrap_or_else(|| T::default()))
}

fn main() {
    let reader = csv::Reader::from_reader(b"\
x,y
0,1
,2
3,
,
5,6
" as &[u8]);

    reader.into_deserialize().for_each(|res: Result<Record, _>| {
        println!("{:?}", res);
    });
}
```

and the output:

```
Ok(Record { x: 0, y: 1, z: 0 })
Ok(Record { x: 0, y: 2, z: 0 })
Ok(Record { x: 3, y: 0, z: 0 })
Ok(Record { x: 0, y: 0, z: 0 })
Ok(Record { x: 5, y: 6, z: 0 })
```

**Comment by RReverser** [comment]
If it works for that structure but not for something simpler like

```rust
#[derive(Debug, Deserialize)]
pub struct Record {
    x: u32,

    #[serde(default)]
    y: u32,
}

/*
x,y
1
*/
```

then it indeed feels way too niche to be actually useful when working with spreadsheets.

**Comment by RReverser** [comment]
I still don't see what are the cons of allowing `serde(default)` for empty fields in a static-sized format where this is the only representation of missing fields, and a pretty common one, especially given that it will still throw errors when `serde(default)` is not specified so it's strictly backwards-compatible, but it seems you are strongly opposed to this feature, so I'll just go ahead and close this discussion.

**Comment by BurntSushi** [comment]
> you are strongly opposed to this feature

Because:

1. The existing behavior is perfectly consistent with other serde deserializers.
2. The "normal" approach to this problem is to use `Option<T>`, where `None` represents empty values.
3. If you can't or don't want to use `Option<T>`, then the work around is borderline trivial, as shown in my example above.

> then it indeed feels way too niche to be actually useful when working with spreadsheets.

Please consider what I save above:

> This might look border-line tautological, but if you're using the same struct to **deserialize multiple similar-but-not-identical** CSV data files, then `serde(default)` actually might be quite useful!

**Comment by RReverser** [comment]
> The existing behavior is perfectly consistent with other serde deserializers.

Other serde deserializers are usually for flexible formats that are able to encode dynamically missing values in the middle of the map, so not really comparable. (I can't think of other formats that have same restriction off the top of my head for 1:1 comparison though.)

> then the work around is borderline trivial, as shown in my example above

It is, but it's still a workaround.
