### ISSUE TITLE
Append option?

### ISSUE THREAD

**Issue by PhdTrollSlayer** [BurntSushi/rust-csv#117]
Is there a append option in this crate?
I need to be able to open the CSV and write in a new line
If not, well, there is my suggestion...

**Comment by BurntSushi** [comment]
The csv crate doesn't care whether it's writing to a new file or whether it's appending to an existing one. All you need to do is [open a file in append mode](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.append) and hand it to the [`from_writer`](https://docs.rs/csv/1.0.0/csv/struct.WriterBuilder.html#method.from_writer) method. You'll like also want to [disable writing the header row](https://docs.rs/csv/1.0.0/csv/struct.WriterBuilder.html#method.has_headers).
