### ISSUE TITLE
What is the path of the `csv` file

### ISSUE THREAD

**Issue by hasanOryx** [BurntSushi/rust-csv#121]
I trying to replicate [this](https://blog.burntsushi.net/csv/) but by `ReaderBuilder::new().from_path` instead of `csv::Reader::from_reader`

So, I wrote my code as below:

```
extern crate csv;
extern crate serde;

#[macro_use]
extern crate serde_derive;

use std::error::Error;
use std::io;
use std::process;
use csv::ReaderBuilder;


#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Record {
    latitude: f64,
    longitude: f64,
    population: Option<u64>,
    city: String,
    state: String,
}
const DATA: &'static str = include_str!("../data/uspop.csv");
fn run() -> Result<(), Box<Error>> {
      let mut rdr = ReaderBuilder::new().from_path(DATA);

        for result in rdr.records() {
        let record = result?;
        println!("{:?}", record);
    }
  /* let mut rdr = csv::Reader::from_reader(io::stdin());
    for result in rdr.deserialize() {
        let record: Record = result?;
        println!("{:?}", record);
        // Try this if you don't like each record smushed on one line:
        // println!("{:#?}", record);
    } */
    Ok(())
}

fn main() {
    if let Err(err) = run() {
        println!("{}", err);
        process::exit(1);
    }
}
```

But I got the below error, from which i understand the app not seeing my csv file:

> rror[E0599]: no method named `records` found for type `std::result::Result<csv::Reader<std::fs::File>, csv::Error>` in the current scope
>   --> src/main.rs:26:27
>    |
> 26 |         for result in rdr.records() {
>    |                           ^^^^^^^

I tried to put my `uspop.csv` file at 3 locations, but looks none of them is working:

1/ In the root, beside the `Cargo.toml`
2/ In the source, beside `main.rs`
3/ In separate folder `root/data/uspop.csv`

But none had been seen, what mistake I'm doing here!

**Comment by BurntSushi** [comment]
In your code, DATA isn't a path, but the file contents itself.

Moreover, the compiler error has nothing to do with whether your file exists it not. The error points out a type conflict. Namely, from_path returns a result, so you need to handle that error.

I recommend scrutinizing the type signatures of the methods you're using more closely.

**Comment by hasanOryx** [comment]
The err is:

> message: "No such file or directory" 

Where shall I put the csv file so that I can read it!

I really wonder why you closed it without answering me!

**Comment by BurntSushi** [comment]
I did answer you:

> In your code, DATA isn't a path, but the file contents itself.

Moreover, the error you showed in your original comment is a compilation error, which is not the same as a runtime

**Comment by hasanOryx** [comment]
I got it done with the below code, my mistake was using the `ReaderBuilder`, thanks for answering [#122](https://github.com/BurntSushi/rust-csv/issues/122)

```
extern crate csv;
extern crate serde;

#[macro_use]
extern crate serde_derive;

use std::error::Error;
use std::process;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct Record {
    latitude: f64,
    longitude: f64,
    population: Option<u64>,
    city: String,
    state: String,
}

fn run() -> Result<(), Box<Error>> {
    use std::env;
    use csv::Reader;
    let executable = env::current_exe()?;
    let path = match executable.parent() {
        Some(name) => name,
        _ => panic!()
    };
    let data_file = format!("{}/data/uspop.csv", path.display());
    let mut rdr = Reader::from_path(data_file)?;
   for result in rdr.deserialize() {
        let record: Record = result?;
        println!("{:?}", record);  // println!("{:#?}", record);
    }
    Ok(())
}

fn main() {
    if let Err(err) = run() {
        println!("{}", err);
        process::exit(1);
    }
}
```
