### ISSUE TITLE
Get data in order

### ISSUE THREAD

**Issue by xperiafan13-rom** [BurntSushi/rust-csv#130]
I cant get data in order, for example,m i parse iris dataset and i get:
These are the values: ["3.3", "6.7", "5.7", "virginica", "2.5"].
These are the values: ["2.3", "virginica", "6.7", "5.2", "3"].
These are the values: ["5", "6.3", "virginica", "1.9", "2.5"].
These are the values: ["2", "6.5", "3", "virginica", "5.2"].
These are the values: ["virginica", "5.4", "6.2", "2.3", "3.4"].
These are the values: ["5.1", "3", "virginica", "1.8", "5.9"].
My code:
fn run() -> Result<(), Box<Error>> {
    let mut rdr = csv::Reader::from_reader(io::stdin());
    let mut training_data = vec![];
    for result in rdr.deserialize() {
        let record: HashMap<String, String> = result.unwrap();
        println!("These are the values: {:?}.", record.values());
    }
    for &TrainingDatum { expected } in &training_data { 
        println!("{}", expected); 
        println!(); 
    }
    Ok(())
}
I need to process all data in order, thanks

**Comment by BurntSushi** [comment]
You're using a hash map, and a hash map's iteration order is unspecified. Use a [`StringRecord`](https://docs.rs/csv/1.0.1/csv/struct.StringRecord.html) instead. It's the first example: https://docs.rs/csv/1.0.1/csv/cookbook/index.html#reading-basic
