### ISSUE TITLE
comments: start of record, or also in fields other than the first?

### ISSUE THREAD

**Issue by dcarosone** [BurntSushi/rust-csv#137]
#### What version of the `csv` crate are you using?

csv 1.02

#### Briefly describe the question, bug or feature request.

I think there's a bug in the handling of comment lines. For a reader built with:

```rust
 let mut rdr = csv::ReaderBuilder::new().comment(Some(b'#'))...
```
lines that start with `#...` are ignored fine.  But a line with a _field_ that starts with a `#`:

``` text
2017-12-29 17:51:32 172.31.20.157 foo bar - 8088 - 172.31.26.68 #34c3 - 404 0 2 0
```

fails to parse with an `UnequalLengths` error:

``` text
UnequalLengths { pos: Some(Position {...}), expected_len: 15, len: 24 }
```

Clearly, it's chopped off the rest of the line, tried to continue on the following line, and found too many fields.

The doc for the comments setting says:

> If the start of a record begins with the byte given here, then that line is ignored by the CSV parser.

which is not quite what is happening here.  I'm not sure if the bug is with the behaviour, or the doc, but they don't match. 

As for desirable behaviour: I can imagine some gnarly CSV that puts comments on the ends of rows, and _maybe_ even mid-line as this is being interpreted, but I think it's a pretty unusual interpretation when comments at the start of line are far more common. It seems like opting in to the current behaviour could be an additional option, but the default (after comments are enabled at all) should be as described in the document.

**Comment by dcarosone** [comment]
This runs successfully, which shows what the crate is doing, at odds with the documentation

```
extern crate csv;

use std::error::Error;
use csv::ReaderBuilder;

fn main() -> Result<(), Box<Error>> {
    let data = "\
city,country,pop
#Concord,United States,42695
Boston,#United States,4628910
United States,4628910
";
    let mut rdr = ReaderBuilder::new()
        .comment(Some(b'#'))
        .from_reader(data.as_bytes());

    if let Some(result) = rdr.records().next() {
        let record = result?;
        assert_eq!(record, vec!["Boston", "United States", "4628910"]);
        Ok(())
    } else {
        Err(From::from("expected at least one record but got none"))
    }
}
```

**Comment by BurntSushi** [comment]
Great find! I agree with your analysis. The docs are indeed correct, and the implementation did not match them. :-) Thankfully, this appears to be easily fixed!

**Comment by BurntSushi** [comment]
The fix for this bug is now on crates.io in `csv 1.0.3`.

**Comment by dcarosone** [comment]
Thanks - but I'm sorry to say, the behaviour doesn't seem to have changed at all.

All I've checked so far is that the rebuild really did use 1.0.3, but it's still rejecting the same line, with the same error and field counts inside.

**Comment by BurntSushi** [comment]
The version of csv isn't what's important. I probably didn't even need to
create a new csv release, it was just habit. What's important is the update
to csv-core. That's where the fix is. Can you confirm you are using the
latest version of csv-core?

**Comment by dcarosone** [comment]
Something is fishy. A small repro program with the same code and input ... isn't. More investigation underway.

**Comment by BurntSushi** [comment]
It's almost certainly due to csv-core not being updated. See my last comment.

**Comment by dcarosone** [comment]
oh, that will be it, for sure.. `cargo update` pulled in a new `csv-core`..

yep, all good now.
