### ISSUE TITLE
Support for missing last field with Serde

### ISSUE THREAD

**Issue by yongqli** [BurntSushi/rust-csv#145]
I would like to support possibly missing last field using Serde; is it possible to get something like the below working?

```
use csv;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Record {
    x: f64,
    y: Option<f64>,
}

fn main() {
    let csv_data = "\
3.0,1.
0.0";
    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(false).flexible(true).from_reader(csv_data.as_bytes());
    println!("{:?}", csv_data);
    for row in rdr.deserialize() {
        let row: Record = row.unwrap();
        println!("{:?}", row);
    }
}
```
[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=72c0b54336307abaeed04dd06e032b71)

The above panics on the last row, I would prefer to get a `Record` with a `None` for `y`.

**Comment by yongqli** [comment]
It would also be nice to support empty `Vec`s for the last field like these:
```
#[derive(Debug, Deserialize)]
struct Record {
    x: f64,
    ys: Vec<f64>,
}
```
[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2176ad5a7a8cb290bc490d0c0b4f11ec)

**Comment by BurntSushi** [comment]
Serde support and "flexible" parsing do not really mix well in CSV format, and I don't see a simple way to solve this. I'd recommend reading `StringRecord`s and writing a helper function to do the parsing manually.

**Comment by akiradeveloper** [comment]
Same issue here. (v1.3)

The workaround I found is adding trailing comma in the shorter row.

In the case mentioned above, change into

```
    let csv_data = "\
3.0,1.
0.0,"; // add trailing comma
```

I think the comma added at the tail asks the deserializer to parse further.

But I prefer the library handle this case because the resulting csv file looks unsound.
