### ISSUE TITLE
Support for serializing/deserializing 128-bit integers

### ISSUE THREAD

**Issue by ian-hamlin** [BurntSushi/rust-csv#149]
#### What version of the `csv` crate are you using?

1.0.5"

#### Briefly describe the question, bug or feature request.

I would like to serialise and deserialise 128-bit integers.

#### Include a complete program demonstrating a problem.

    #[test]
    fn integer_128() {
        let got = serialize(12345_u128);
        assert_eq!(got, "12345\n");
    }

#### What is the observed behavior of the code above?

`---- serializer::tests::integer_128 stdout ----
thread 'serializer::tests::integer_128' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Serialize("u128 is not supported"))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

#### What is the expected or desired behavior of the code above?

The integer would be serialised.

**Comment by ian-hamlin** [comment]
I attempted to add support for what I need here:

https://github.com/ian-hamlin/rust-csv

And I added a sample app here:

https://github.com/ian-hamlin/rust-csv-128

It all seems to work OK, when pointing at my branch, but I'm not really sure I covered all the bases.

**Comment by BurntSushi** [comment]
@ian-hamlin Thanks! Do you want to submit a PR?
