### ISSUE TITLE
add a position method to csv::Error (and probably csv::ErrorKind)

### ISSUE THREAD

**Issue by mamcx** [BurntSushi/rust-csv#156]
#### What version of the `csv` crate are you using?
1.0.7

#### Briefly describe the question, bug or feature request.

I'm reading csv output from another program, and if I get a deserialize error, can't see how extract with line/text cause it, only parsing error:

> Position { byte: 111, line: 2, record: 1 }), err: DeserializeError { field: Some(4), kind: ParseBool(ParseBoolError { _priv: () })

Now I wish to output something like

```
Position { byte: 111, line: 2, record: 1 }), err: DeserializeError { field: Some(4), kind: ParseBool(ParseBoolError { _priv: () })
Line:
sample
4
```

#### Include a complete program demonstrating a problem.

Now, reading with` rdr.records()` allow me to see the data, trim, then see the failed data on err:

```rust
        let mut rdr = csv::Reader::from_reader(reader);
        let mut rows: Vec<T> = Vec::new();
        let headers = rdr.headers().context(CVSError {})?.clone();
        for result in rdr.records() {
                let mut line = result.context(CVSError {})?;
                line.trim();
                let record: Result<T, _> = line.deserialize(Some(&headers)).context(CVSError {});
                match value {
                    Ok(record) => {                       
                        rows.push(record);
                    }
                    Err(err) => {
                       //print line
                    }
            }
```

 But wonder if exist a way that allow to keep the use of serve and deserialize yet show me the data on fail:

```rust
            for result in rdr.records().deserialize() {
                let record: T = result.context(CVSError {})?;
                match value {
                    Ok(record) => {                       
                        rows.push(record);
                    }
                    Err(err) => {
                       //what to print???
                    }
                }
                rows.push(record);
            }
```

**Comment by BurntSushi** [comment]
Please provide a complete program that I can compile and run. Please also provide input, actual output and expected output.

In particular, I'm not seeing why you can't just read the error information directly: https://docs.rs/csv/1.0.7/csv/enum.ErrorKind.html

But I don't know because I can't compile your code. Please remove the guess work and provide a complete example.

**Comment by mamcx** [comment]
Ok, I put a more minimal sample:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0bf0932a448c5490838491b640279c08
```rust
    extern crate csv;
    extern crate serde;
    
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Serialize, Deserialize)]
    struct Failed {
        field: usize,
    }
    #[test]
    fn cvs() -> Result<(), Box<std::error::Error>> {
        let data = "\
     city,country,pop
     Boston,United States,42695
     Concord,United States,42695
     ";

        let mut rdr = csv::Reader::from_reader(data.as_bytes());
        for result in rdr.deserialize() {
            let record: Failed = result?;
            println!("{:?}", record);
        }
        Ok(())
    }
```

Now, how see which line cause the issue?

**Comment by BurntSushi** [comment]
As I said in my previous comment, just look at the error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=442d3ea379f09468ea24794157450321

Here's the code:

```rust
extern crate csv;
extern crate serde;

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
struct Failed {
    field: usize,
}

fn main() -> Result<(), Box<std::error::Error>> {
    let data = "\
city,country,pop
Boston,United States,42695
Concord,United States,42695
";

    let mut rdr = csv::Reader::from_reader(data.as_bytes());
    for result in rdr.deserialize() {
        let record: Failed = match result {
            Ok(record) => record,
            Err(err) => {
                match *err.kind() {
                    csv::ErrorKind::Deserialize { pos: Some(ref pos), .. } => {
                        println!("line: {}", pos.line());
                    }
                    _ => {
                        println!("not a deserialize error");
                    }
                }
                continue;
            }
        };
        println!("{:?}", record);
    }
    Ok(())
}
```

It would be nicer if `Error` had a `fn position(&self) -> Option<&Position> { ... }` defined on it, so that it would be easier to get access to it without matching on each different error that could possibly contain a position.

**Comment by BurntSushi** [comment]
Please don't close this. I changed the title to reflect an enhancement to make the task easier by adding a new `position` method to `Error`.
