### ISSUE TITLE
Using seek to reset to start position no longer skips header

### ISSUE THREAD

**Issue by vilhelmo** [BurntSushi/rust-csv#168]
First off, I'm new to rust and I'm aware what I was trying to do might not be the most rust-like way of doing it. 
With that being said, I found that if I get the original position of a reader, read some records and then seek with that same start position, the second pass will include the headers of the csv, even though the first pass skipped it. 

#### What version of the `csv` crate are you using?
csv = "1.1.1"

#### Briefly describe the question, bug or feature request.

Want to clarify that the seek behavior works like this by design and that it's not a bug.

#### Include a complete program demonstrating a problem.
`use std::error::Error;
use std::io;
use csv::Reader;

fn example() -> Result<(), Box<dyn Error>> {
    let data = "\
city,country,popcount
Boston,United States,4628910
Concord,United States,42695
";
    let rdr = Reader::from_reader(io::Cursor::new(data));
    let mut iter = rdr.into_records();
    let start_pos = iter.reader().position().clone();
    // First print all the 2 records by iterating over them
    loop {
        let n = iter.next();
        if let Some(result) = n {
        	let record = result?;
	        println!("{:?}", record);
	    } else {
	    	break;
	    }
    }

    // Now seek the reader back to start_pos. 
    // I expected this to be able to read back the same records as the first time.
    iter.reader_mut().seek(start_pos)?;
    let mut iter = iter.into_reader().into_records();
    if let Some(result) = iter.next() {
        let record = result?;
        assert_eq!(record, vec!["Boston", "United States", "4628910"]);
        Ok(())
    } else {
        Err(From::from("Expected at least one record but got none"))
    }
}

fn main() {
	assert!(!example().is_err());
}`
#### What is the observed behavior of the code above?

No panics, print out the records once.

#### What is the expected or desired behavior of the code above?

Panics, the assert in the example function fails.

**Comment by BurntSushi** [comment]
As you mentioned, this is [correct and documented behavior](https://docs.rs/csv/1.1.1/csv/struct.Reader.html#method.seek).

I'm not sure what you're expecting for here. If you seek to an arbitrary position in the underlying file, then the reader doesn't know whether you're at a header row or not.

Your best recourse is probably #164, which will let you clear the reader's internal state.
