### ISSUE TITLE
Quote chars incorrectly included in StringRecord field

### ISSUE THREAD

**Issue by jgarzik** [BurntSushi/rust-csv#180]
#### What version of the `csv` crate are you using?

1.1.1

#### Briefly describe the question, bug or feature request.

Googling for CSV examples yields the following as one of the first links: https://people.sc.fsu.edu/~jburkardt/data/csv/biostats.csv

The first quoted-string column is parsed correctly.  The second quoted-string column unexpectedly includes leading and trailing quotes.

#### Include a complete program demonstrating a problem.

```
use csv::{ReaderBuilder, StringRecord, Trim};
use std::path::Path;

fn main() {
    let path = Path::new("biostats.csv");
    let mut rdr = ReaderBuilder::new()
        .has_headers(true)
	.trim(Trim::All)
	.from_path(path).unwrap();

    for res in rdr.records() {
        println!("record:");
        match res {
	    Err(_e) => { panic!("records() iteration failed"); },
	    Ok(sr) => {
	        for field in sr.iter() {
		    println!("field: {:?}", field);
		}
	    }
	}
    }
}
```

#### What is the observed behavior of the code above?

```
record:
field: "Alex"
field: "\"M\""
field: "41"
field: "74"
field: "170"
record:
field: "Bert"
field: "\"M\""
field: "42"
field: "68"
field: "166"
record:
field: "Carl"
field: "\"M\""
field: "32"
field: "70"
field: "155"
record:
field: "Dave"
field: "\"M\""
field: "39"
field: "72"
field: "167"
...
```

#### What is the expected or desired behavior of the code above?

The "Sex" column is not quoted different from other columns.

**Comment by BurntSushi** [comment]
There is nothing incorrect happening here. Your CSV data is malformed. Python should have the same interpretation of your data as this library, for example.

See my comment here for an example of the same problem: https://github.com/BurntSushi/rust-csv/issues/181#issuecomment-552438128
