### ISSUE TITLE
Examples in README and cookbook appear to be out of date

### ISSUE THREAD

**Issue by asmyers** [BurntSushi/rust-csv#183]
Examples appear to be out of date, using csv version 1.1.  For instance, the example in the README references the type `Result<(), Box<dyn Error>>`.  However, it appears that with CSV 1.1.1 the `Result` type defined at line 10 in `errors.rs` only has a single type parameter.

**Comment by BurntSushi** [comment]
The examples are correct. The Result in the example isn't csv::Result.
