### ISSUE TITLE
method `detail` is not a member of trait `StdError`

### ISSUE THREAD

**Issue by losvedir** [BurntSushi/rust-csv#20]
Just upgraded my nightly rust to the `2015-1-23` build, and now running into compilation errors on one of my projects:
```
   Compiling csv v0.12.9
/Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/csv-0.12.9/src/lib.rs:317:5: 317:66 error: method `detail` is not a member of trait `StdError`
/Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/csv-0.12.9/src/lib.rs:317     fn detail(&self) -> Option<String> { Some(self.to_string()) }
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `csv`.
```

This sounds like it's related to https://github.com/rust-lang/rust/commit/3cb9fa26ef9905c00a29ea577fb55a12a91c8e7b . I tried just deleting the `detail` method indicated by the error message (since `cause` was already implemented, and the RFC made it sound like that's what it turned into), but that led to another problem that I didn't understand. So I gave up.

But here's an issue, anyway.

**Comment by BurntSushi** [comment]
No worries! I'll fix this tonight.

**Comment by alexchandel** [comment]
Possible to get a faster fix? I was using this for a project.

**Comment by BurntSushi** [comment]
Not from me. I'm at work.

**Comment by BurntSushi** [comment]
If you really need something working, I'd suggest moving back to an older version of Rust nightly.

**Comment by alexchandel** [comment]
@BurntSushi problem is rustc-serialize was updated. I'll send you a PR in a minute fixing this.

**Comment by BurntSushi** [comment]
@alexchandel Thanks. :-) If I get a PR that passes tests, I can update `crates.io`.

(N.B. You can set your `Cargo.toml` to use an older version of `rustc-serialize`.)

**Comment by alexchandel** [comment]
Want me to bump the VN?

**Comment by BurntSushi** [comment]
No thanks. I have a `cargo-up` script that handles all that nonsense. :-)
