### ISSUE TITLE
new format qvs20

### ISSUE THREAD

**Issue by LucianoBestia** [BurntSushi/rust-csv#205]
Hello,
@BurntSushi, I like your work on rust-csv.
I am trying to make a proposal for a new format, that is similar to csv.
I would appreciate, if you give it a look.
https://github.com/LucianoBestia/QVS20
I will need a lot of time to make something useful, but I think the idea is worth it.
I hope you will like the new format QVS20.

**Comment by BurntSushi** [comment]
Interesting! I'm not sure I'll have a lot of time to look at it unfortunately. I wish you luck with it!
