### ISSUE TITLE
Using UTF-8 delimiters

### ISSUE THREAD

**Issue by SuperFluffy** [BurntSushi/rust-csv#209]
I am dealing with a file that looks like this:

```
Royston, Mike¶5
Royston, Mike, 1947-¶5
```

So `¶` is used as a delimiter. If I read `ReaderBuilder` correctly, then `ReaderBuilder::delimiter` expecting a `u8` restricts the delimiter to ASCII?

Is there any way to throw this data at `rust-csv` or will I need to parse each line manually?

**Comment by BurntSushi** [comment]
Only ASCII delimiters are supported and there are no plans to change this.

**Comment by SuperFluffy** [comment]
That's alright, thank you for the clarification and your work on `rust-csv`! Just wanted to make sure that I wasn't blind and overlooked something.
