### ISSUE TITLE
how can i append a line into my csv file using this crate?

### ISSUE THREAD

**Issue by SakuraWHU** [BurntSushi/rust-csv#225]
I tried append one line, but found only r+|w.
Moreover, func Writer::new() is private!! 
which really confuse me!
if you will help me slove this problem, i will be appreciate!!

**Comment by BurntSushi** [comment]
In the future, please consider providing more detail to your question. In particular, please fill out the issue template that you deleted. Showing what you've tried would be helpful, for example.

In any case, I took a _guess_ at what it is you're trying to accomplish. Here is a program that appends one record to a CSV file:

```
$ cat Cargo.toml
[package]
name = "csv-225"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1"

$ cat data.csv
header1,header2,header3
foo,bar,baz

$ cat src/main.rs
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let file = std::fs::OpenOptions::new()
        .append(true)
        .open("data.csv")?;
    let mut wtr = csv::Writer::from_writer(file);
    wtr.write_record(&["quux", "fox", "rox"])?;
    wtr.flush()?;
    Ok(())
}
```

I then compiled with `cargo build --release` and ran `./target/release/csv-225`. After running, the contents of `data.csv` are now:

```
$ cat data.csv
header1,header2,header3
foo,bar,baz
quux,fox,rox
```

The key here is actually not anything to do with this crate. And I'm not sure why you were trying to use `Writer::new`. Even if it were public, it wouldn't solve your problem. The key is using [`std::fs::OpenOptions`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html) to open a file in append mode. At that point, it's just a simpler matter of handing that file descriptor to the CSV writer.
