### ISSUE TITLE
reader read errror with leading double quote

### ISSUE THREAD

**Issue by lichuan6** [BurntSushi/rust-csv#228]
Hi,

The `read_record` returns an error when there's a leading double quote in some field in csv.

```
Error : Error(UnequalLengths { pos: Some(Position { byte: 17, line: 2, record: 1 }), expected_len: 3, len: 2 })
```

Here's the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=692038b379bf9452bda3b7d56b7f9abf).

Thanks for your reply.

**Comment by BurntSushi** [comment]
That's correct. Your description is incomplete. It's not just a leading quote. It's a leading quote without a closing quote. In other words, it's malformed CSV.
