### ISSUE TITLE
Question about (de)serializing vectors

### ISSUE THREAD

**Issue by corvusrabus** [BurntSushi/rust-csv#254]
Hi, thanks for providing this great crate. 
Currently, when I am using the crate to serialise a vector inside a struct it will be flattened, so say I have:

struct A {
a : String,
b : Vec\<i64>
}

and I have a flexible writer, then two As {"Hello",[1,2,3]},  {"Bye", [4,5,6,7]} would be serialized to
"Hello", 1,2,3,
"Bye", 4,5,6,7

Is there any way I can tell the CSV writer to serialize it to
"Hello", [1,2,3]
"Bye", [4,5,6,7] 
?

**Comment by BurntSushi** [comment]
Please provide a complete Rust program, any relevant inputs, actual output and desired output.

**Comment by corvusrabus** [comment]
**Program**

use std::io;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug)]
struct A {
    a: String,
    b: Vec<i64>,
}

fn main() {
    let x = A { a: "Hello".to_string(), b: vec![1, 2, 3] };
    let y = A { a: "Bye".to_string(), b: vec![4, 5, 6, 7] };
    let mut w = csv::WriterBuilder::new()
        .flexible(true).has_headers(false).from_writer(io::stdout());
    w.serialize(x);
    w.serialize(y);
}

**Actual output**
Hello,1,2,3
Bye,4,5,6,7
**Desired output**
Hello,[1,2,3]
Bye,[4,5,6,7]

**Comment by ammernico** [comment]
Hi, I have the same problem. But I guess the behavior is known since it's documented here:
`Nested containers are flattened to their scalar components`
https://docs.rs/csv/1.3.0/csv/struct.Writer.html#non-struct-containers

Is this behavior desired? It seems an odd choice for serializing into csv

**Comment by BurntSushi** [comment]
It's not only desired, in not aware of any reasonable alternative other than disallowing it entirely. If you call it odd, why not say why it's odd and suggest an alternative behavior?

The OP's suggestion is not reasonable here because it layers a completely different serialization format that is not CSV on top of CSV.
