### ISSUE TITLE
[suggestion] implement  `std::iter::DoubleEndedIterator`

### ISSUE THREAD

**Issue by petar-dambovaliev** [BurntSushi/rust-csv#263]
Hello, i have a use case for parsing backwards.
I am writing a library to calculate tax returns from stock sales and some brokers export large csv files containing all transactions for a given period.
The rows are ordered as first at the top and last at the bottom.
If i can use `DoubleEndedIterator::next_back`, i can prevent reading the whole file in memory, to construct a `VecDeque`.

**Comment by BurntSushi** [comment]
It's a nice idea, and i think it may be theoretically possible, but is a ton of work. It would require writing a reverse CSV parser, for example. And at the API level, it would require Seek.

I don't see this happening, sorry.

**Comment by petar-dambovaliev** [comment]
> It's a nice idea, and i think it may be theoretically possible, but is a ton of work. It would require writing a reverse CSV parser, for example. And at the API level, it would require Seek.
> 
> I don't see this happening, sorry.

I will fork and you can possibly merge it, if i do it well.
