### ISSUE TITLE
StringRecords back to original csv string functionality

### ISSUE THREAD

**Issue by alexhallam** [BurntSushi/rust-csv#266]
Thank you for taking the time to file a bug report. The following describes
some guidelines to creating a minimally useful ticket.

Above all else: do not describe your problem, **SHOW** your problem.

#### What version of the `csv` crate are you using?

`csv = "1.1"`

#### Briefly describe the question, bug or feature request.

Does functionality exist to convert `StringRecords` back to the original csv string?

#### Include a complete program demonstrating a problem.

```rust
use csv::Reader;
use csv::StringRecord;

fn main() {
    let data = "\
City,State,Population,Latitude,Longitude
Davidsons Landing,AK,,65.2419444,-165.2716667
Kenai,AK,7610,60.5544444,-151.2583333
Oakman,AL,,33.7133333,-87.3886111";

    let mut rdr: Reader<&[u8]> = csv::ReaderBuilder::new()
        .has_headers(false)
        .delimiter(b',')
        .from_reader(data.as_bytes());
}
```

#### What is the observed behavior of the code above?

None

#### What is the expected or desired behavior of the code above?

I would like to get back to the original string.

```
"
City,State,Population,Latitude,Longitude
Davidsons Landing,AK,,65.2419444,-165.2716667
Kenai,AK,7610,60.5544444,-151.2583333
Oakman,AL,,33.7133333,-87.3886111"
```

**Comment by BurntSushi** [comment]
Your program doesn't have any output... And the example output you've provided would be _multiple_ `StringRecord`s...

But to answer your question, yes. To write CSV data, you should use `csv::Writer`.

**Comment by alexhallam** [comment]
Thanks, I thought that `csv::Writer` was printing. I did not realize I could save the string to a variable. This answers my question.

**Comment by BurntSushi** [comment]
It is for printing. There are several examples in the docs that show how to "print" to a `String`. For example: https://docs.rs/csv/latest/csv/struct.Writer.html#method.write_record
