### ISSUE TITLE
Automatically transcode UTF-16LE encoded files to UTF-8 when reading CSV files

### ISSUE THREAD

**Issue by jqnatividad** [BurntSushi/rust-csv#270]
#### What version of the `csv` crate are you using?
 csv 1.1.6

#### Briefly describe the question, bug or feature request.
Unlike other modern operating systems, [Windows' default text encoding is UTF16-LE](https://stackoverflow.com/questions/66072117/why-does-windows-use-utf-16le).

So when writing a CSV file to stdout redirecting to a file, it creates a UTF16-LE encoded CSV file which cannot be read by  `csv::Reader` as it expects  UTF8.  

It would be nice if `csv::Reader` automatically transcodes to UTF8 - perhaps with [encoding_rs_io]( https://docs.rs/encoding_rs_io/latest/encoding_rs_io/index.html).

#### Include a complete program demonstrating a problem and the observed behavior
For example, using [`xsv 0.13.0`](https://github.com/BurntSushi/xsv) (which extensively uses the csv crate) whirlwind tour worldcitiespop.csv file on Windows:

```
xsv stats worldcitiespop.csv > wcstats.csv
xsv stats worldcitiespop.csv --output wcstats2.csv
```
Results in these files:
[wcstats.csv](https://github.com/BurntSushi/rust-csv/files/8192865/wcstats.csv)
[wcstats2.csv](https://github.com/BurntSushi/rust-csv/files/8192866/wcstats2.csv)

Examining these files with `xsv table`, we get:

```
xsv table wcstats.csv
CSV error: record 1 (line: 1, byte: 115): found record with 1 fields, but the previous record has 9 fields
```
```
xsv table wcstats2.csv
field       type     sum                 min            max            min_length  max_length  mean                stddev
Country     Unicode                      ad             zw             2           2
City        Unicode                       bab el ahmar  Þykkvibaer     1           91
AccentCity  Unicode                       Bâb el Ahmar  ïn Bou Chella  1           91
Region      Unicode                      00             Z9             0           2
Population  Integer  2289584999          7              31480498       0           8           47719.570633597126  302885.5592040396
Latitude    Float    86294096.37312101   -54.933333     82.483333      1           12          27.188165808468785  21.95261384912504
Longitude   Float    117718483.57958724  -179.9833333   180            1           14          37.08885989656418   63.223010459241635
```

Interestingly, piping the file from `xsv stats` to `xsv table` presents a different issue with unicode encoding - note the min\max values for the City and AccentCity fields:
```
xsv stats .\worldcitiespop.csv | xsv table
field       type     sum                 min             max             min_length  max_length  mean                stddev
Country     Unicode                      ad              zw              2           2
City        Unicode                       bab el ahmar   ??ykkvibaer     1           91
AccentCity  Unicode                       B??b el Ahmar  ??n Bou Chella  1           91
Region      Unicode                      00              Z9              0           2
Population  Integer  2289584999          7               31480498        0           8           47719.570633597126  302885.5592040396
Latitude    Float    86294096.37312101   -54.933333      82.483333       1           12          27.188165808468785  21.95261384912504
Longitude   Float    117718483.57958724  -179.9833333    180             1           14          37.08885989656418   63.223010459241635
```

#### What is the expected or desired behavior of the code above?

`csv::Reader` automatically transcodes to UTF8 when required.

**Comment by BurntSushi** [comment]
This is beyond the scope of this crate. If you need it, then there's no reason why callers can't use encoding_rs_io themselves. Similarly, there's no compelling reason IMO for the csv crate to do it for you.

Now arguably xsv should use encoding_rs_io though.

**Comment by jqnatividad** [comment]
Thanks @BurntSushi! I'll just use encoding_rs_io in my project...
