### ISSUE TITLE
Please release current master as 1.1.7

### ISSUE THREAD

**Issue by ColinFinck** [BurntSushi/rust-csv#271]
41c71ed353a71526c52633d854466c1619dacae4 brought us `itoa` 1.x, but it's not yet available in an official `csv` release.
Should be fairly straightforward to release current master as 1.1.7

CC @BurntSushi @waywardmonkeys

**Comment by evolvedmicrobe** [comment]
Hi @BurntSushi,

Thanks for writing this crate and making it available!  That said, is this project still active?  Noticed last commit was over a year ago, and also just tripped over the `itoa` issue referred to here, wondering I should fork or wait for an update to resolve.

Thanks again, and hope you're doing well,
Nigel

**Comment by BurntSushi** [comment]
I don't provide release schedules for things in my free time. If you need to make progress, then you should do what you need to do to make progress.

This project is still active yes. I do not consider any recent changes to be urgent enough to justify going out of my way to make a release. It at least, I don't know of any reason why I should.

**Comment by BurntSushi** [comment]
What is the "itoa issue"? That a dependency is duplicated in your tree?

**Comment by BurntSushi** [comment]
> Noticed last commit was over a year ago

The last commit was less than six months ago.

**Comment by evolvedmicrobe** [comment]
Thanks for the quick response!  Regarding: `I don't provide release schedules for things in my free time`, totally agree, was just curious if we should fork or if there was likely to be another release coming down the pipe at some point, and glad to hear the project is still active.

And yeah, the `itoa` issue is just trying to remove duplicate dependencies across an ecosystem of crates we use.  Apologies on the last commit actually being in Dec. of this year as well, a thinko on my part.

**Comment by Nilstrieb** [comment]
`itoa` 0.4 contains unsound uses of `std::mem::uninitialized` (uninit integers). If we want to issue a future-compatibility-warning on that, which we want to do at some point, it would be nice if `csv` didn't use it anymore.

**Comment by jacobsvante** [comment]
What @Nilstrieb mentions sounds like something that should warrant a new release asap... Right?

**Comment by BurntSushi** [comment]
I'll get to it when I can.

**Comment by RalfJung** [comment]
> itoa 0.4 contains unsound uses of std::mem::uninitialized (uninit integers). If we want to issue a future-compatibility-warning on that, which we want to do at some point, it would be nice if csv didn't use it anymore.

Status update on that: latest rustc nightly mitigates that UB by making `mem::uninitiailized` actually initialize the memory, which makes it slower. That means users of itoa 0.4 will see a performance degradation.

**Comment by oherrala** [comment]
I came here because [`cargo-careful`](https://crates.io/crates/cargo-careful) (nice tool!) warns about uninitialized memory and this crate is the user of `itoa 0.4.8`:

```
panicked at 'attempted to leave type `[u8; 40]` uninitialized, which is invalid', /Users/oherrala/.cargo/registry/src/github.com-1ecc6299db9ec823/it
oa-0.4.8/src/lib.rs:135:29
```

**Comment by extrawurst** [comment]
looking forward to a new release containing the `itoa` upgrade

**Comment by BurntSushi** [comment]
`csv 1.2.0` is now on crates.io.
