### ISSUE TITLE
CSV Deserialization is much slower than xsv row counting

### ISSUE THREAD

**Issue by kszlim** [BurntSushi/rust-csv#274]
#### What version of the `csv` crate are you using?

1.1.6

#### Briefly describe the question, bug or feature request.

CSV deserialization via serde is much slower than counting the rows via xsv

#### Include a complete program demonstrating a problem.
Deps:
```
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
```

Code:
```rust
use csv::ReaderBuilder;
use serde::Deserialize;

#[derive(Debug, Deserialize, PartialEq)]
enum Side {
    #[serde(rename = "b")]
    Bid,
    #[serde(rename = "a")]
    Ask,
}

#[derive(Debug, Deserialize, PartialEq)]
enum UpdateType {
    #[serde(rename = "snap")]
    Snap,
    #[serde(rename = "delta")]
    Delta,
    #[serde(rename = "set")]
    Set,
}

#[derive(Debug, Clone, Copy, Deserialize)]
struct UpdateId(u64);

#[derive(Debug, Deserialize)]
struct BinanceUpdate {
    timestamp: Timestamp,
    first_update_id: UpdateId,
    last_update_id: UpdateId,
    side: Side,
    update_type: UpdateType,
    price: Price,
    #[serde(rename = "qty")]
    quantity: Quantity,
    #[serde(rename = "pu")]
    last_id_of_last_batch: UpdateId,
}

#[derive(Debug, Clone, Copy, Deserialize)]
struct Price(f64);
#[derive(Debug, Clone, Copy, Deserialize)]
struct Quantity(f64);
#[derive(Debug, Clone, Copy, Deserialize)]
struct Timestamp(u64);


fn main() {
    let mut reader = ReaderBuilder::new()
        .delimiter(b',')
        .from_path("data.csv")
        .unwrap();
    let mut count = 0;
    for update in reader.deserialize::<BinanceUpdate>() {
        count += 1;
    }
    println!("Count: {:}", count);
}
```

Data (I'm processing about 13GB of data similar to what's shown):
```
symbol,timestamp,first_update_id,last_update_id,side,update_type,price,qty,pu
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45503.10,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45503.20,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45505.90,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45506.00,2.173,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45512.10,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45513.60,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45513.70,2.285,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45514.90,0.000,1342446841760
BTCUSDT,1648771200050,1342446841841,1342446846375,a,set,45515.50,1.051,1342446841760
```

#### What is the observed behavior of the code above?

I deserialize at a rate of about 185MB/s, whereas counting the rows via xsv is saturating my SSD at 590MB/s

#### What is the expected or desired behavior of the code above?

From digging around, it seems like my program should at most be ~2x slower than just iterating through the records, so I'm a bit curious if there's any obvious performance issue here.

**Comment by BurntSushi** [comment]
I'm not quite sure where you got the 2x expectation from, but serde deserialization is of course going to be slower because it is doing additional work. How much slower depends on how much additional work is done (like the number of fields) and the nature of that work (allocs, parsing floating point, etc).

**Comment by kszlim** [comment]
> I'm not quite sure where you got the 2x expectation from, but serde deserialization is of course going to be slower because it is doing additional work. How much slower depends on how much additional work is done (like the number of fields) and the nature of that work (allocs, parsing floating point, etc).

Ah, I got that from:

https://github.com/BurntSushi/rust-csv/issues/87#issuecomment-325199285

Where you said:

> That's twice as slow as just counting the records. Instinctively, that feels about right. Looking at a profile of the aforementioned program doesn't show anything amiss.

If you think the performance I'm getting is normal, then don't worry about it and close this issue, I just assumed I was doing something wrong.

**Comment by BurntSushi** [comment]
Aye, I'll close this issue.

I don't see anything obviously wrong. If you had strings or other allocs in your record type, then you might be able to get away with using, e.g., ByteRecord::deserialize_into. Otherwise, you could always profile your program and look at where the hot spots are.

**Comment by kszlim** [comment]
Yeah, I created a flamegraph, and pretty much all the time is spent in:

`csv::reader::Reader<R>::read_record` and `csv::deserializer::deserialize_string_record`

**Comment by BurntSushi** [comment]
Right. I would expect to see some calls inside those routines show up too. For example, float parsing.
