### ISSUE TITLE
Writer support for padding / formatting / prettifying

### ISSUE THREAD

**Issue by samdenty** [BurntSushi/rust-csv#279]
It'd be nice if the `WriterBuilder` had an option for pretty-printing the output.

```rust
WriterBuilder::new().prettify(true).from_path("./a.csv")
```

**Comment by BurntSushi** [comment]
I'm going to pass. Prettifying very likely changes the meaning of the data. And there's no real reason it has to be in this crate. You can combine the output of a Writer with the tabwriter crate quite easily.

Plus, the idea that this request is as simple as a single "prettify" boolean option is a little unrealistic. Prettification can be done in a lot of different ways with a number of different knobs. That isn't what this crate specializes in.

**Comment by samdenty** [comment]
```rust
  let mut tw = TabWriter::new(std::io::stdout());
  let mut buf = BufWriter::new(Vec::new());

  {
    let mut wtr = csv::Writer::from_writer(&mut buf);
    // write to wtr here
    wtr.flush()?;
  }

  let csv = String::from_utf8(buf.into_inner()?)?.replace(",", ",\t");
  tw.write_all(csv.as_bytes())?;
  tw.flush()?;
```
