### ISSUE TITLE
Expected a record with length at least 7, but got a record with length 6.

### ISSUE THREAD

**Issue by ndarilek** [BurntSushi/rust-csv#28]
Trying to parse [https://data.texas.gov/download/r4v4-vz24/application/zip](this GTFS data) with [https://github.com/ndarilek/gtfs-rs](this GTFS parser) I'm building. Unfortunately, I'm running into an issue with optional data. In particular, [https://github.com/ndarilek/gtfs-rs/blob/master/examples/stats.rs](this example) fails on the above dataset (put it in _examples/data/gtfs.zip_) because the first line of agency.txt has 6 fields, not 7. Even so, many of these fields are optional, and I'd like to represent them with Option<String> instead of as something that may or may not be empty.

Fairly new to Rust. Not sure what the best way to achieve this in a typesafe way is. Since my file has headers, and indeed the headers are required by the GTFS spec, it might be nice if I could import into an associative array keyed off of those headers, since I don't know what kind of data transit agencies might provide. If I convert some of the types in the decode tuple to Option, the expected record length seems to grow (I.e. it expects 8-9 fields, not 7.)

Any help appreciated. Thanks.

**Comment by BurntSushi** [comment]
This should be supported when you set `flexible(true)` on the reader: http://burntsushi.net/rustdoc/csv/struct.Reader.html#method.flexible

In particular, this code should work, but the CSV reader reports the error as you describe: https://gist.github.com/e3f651b41a7c1d8ed3ae

Here are a few notes:

1. Unless your CSV data is truly dynamic, you probably don't want an associative array, although one is easy to build. Instead, you'll want to define a struct and decode into it like in this example: https://github.com/BurntSushi/rust-csv/blob/master/examples/nfl_plays.rs
2. If your header row has 6 fields but other rows have more than that, then the first 6 fields of those rows must correspond to the headers. There's really no other tenable interpretation in the general case. If your CSV files require more nuance than this, then you'll need to implement custom logic.
3. If your header row has 6 fields but other rows have *fewer* than that, then the last N fields are optional.
4. Technically speaking, rows of varying length are **not** valid CSV data according to the specification. This is why you must allow it explicitly with `flexible(true)`.

I'll work on fixing this later today. Thanks for the report!

**Comment by ndarilek** [comment]
Thanks. I don't think I need differing length lines, but the GTFS spec
for agency.txt defines 7 fields and the dataset I linked only includes
6. Some are optional, and since I'm trying to make this deal with any
odd combination of fields transit agencies might throw at me, I thought
the associative array approach might be easier. In particular, my
dataset includes one optional field (agency_id) but omits the last
optional field (agency_fare_url). Given that this is the first dataset
I've looked at, the level of inconsistency I'm already seeing worries me. :)

**Comment by BurntSushi** [comment]
Right. I mean that the struct should be allowed to be bigger. Right now, the decoder is pretty strict about it.

Note that the names in your struct don't matter; the *order* matters. This means that it never makes sense for optional fields to come before required fields. I see now why an associative array would be useful, or alternatively, a decoder that matches struct member names with header names.

**Comment by BurntSushi** [comment]
If you just want to stuff each row in a hash map, you can use this: https://gist.github.com/30d5e85d611acc8632f0 --- It's pretty wasteful though.

Basically, the CSV library just doesn't do anything with header names. It's aware of a header row, but otherwise doesn't assign any specific semantic value to a header name. Maybe it should.
