### ISSUE TITLE
Consider a mechanism to skip map's, or allow for a default operation

### ISSUE THREAD

**Issue by chriskyndrid** [BurntSushi/rust-csv#282]
#### What version of the `csv` crate are you using?
1.1.6

#### Briefly describe the question, bug or feature request.

It would be beneficial to allow passing an argument to the writer to skip(e.g. return "") properties of structures that are a map. I'm using the crate to export CSV data from database tables that are represented by a structure. Many of those tables have columns of the type jsonb, which are represented as:

```rust
pub meta_json: Option<serde_json::Value>,
```

When those  fields are encountered the writer raises an error indicating:

serializing maps is not supported...

I understand the rationale for that.

#### Include a complete program demonstrating a problem.

```rust
    fn to_csv(self) -> Result<String> {
        let mut writer = csv::Writer::from_writer(vec![]);
        for item in self {
            writer.serialize(item)?;
        }

        Ok(String::from_utf8(writer.into_inner()?)?)
    }
```

#### What is the observed behavior of the code above?

CSV writer rationally raises an error. 

#### What is the expected or desired behavior of the code above?

Allow to supply an argument to writer to skip map's. Alternatively provide a decorator for structure properties that indicates a desired behavior on a specific map. E.G. convert the map to a json string first.

**Comment by chriskyndrid** [comment]
Thanks for the quick reply. I didn't realize I could do it directly with serde, I'll investigate that further. 

As for the why, well, so it doesn't raise an error and continues processing. In my situation, the data in those columns isn't particularly important relative to the rest of the information. Considering your comments elsewhere on processing maps, it would seem reasonable to give the caller the option of determining whether they are willing to accept an incomplete output, rather than terminating the process.

**Comment by BurntSushi** [comment]
Basically, I would expect [`serde(skip)` to just work](https://serde.rs/field-attrs.html#skip) in this case.

Similarly, you can _certainly_ implement `Serialize` however you want for your own types, or even just [specify your own serialization function](https://serde.rs/field-attrs.html#serialize_with) for specific fields without the ceremony of defining your own types (like in the case of `json::Value`).

**Comment by chriskyndrid** [comment]
@BurntSushi 

Thanks, I appreciate the feedback and pointers, it's very helpful. 

In my case, I have over over a hundred structures, with about a dozen json::Value types in various places. The existing properties should serialize/deserialize according to the current configuration _except_ when exporting to CSV format. Implementation wise, this is being used to allow users in the UI to quickly hit a 'CSV' button for the data they're viewing on a given screen. 

I'll have to think a little about how I might approach it further to keep things simple. 

Thanks and have a great day. I'll go ahead and close the issue.

**Comment by BurntSushi** [comment]
Ah I see. Hmm. No obvious and clean solution to that sticks out to me. I do somewhat suspect that the design or intent is unfortunately flawed, because CSV can't encode arbitrary values like, say, JSON can. So there really ought to be some kind of place for some fundamental conversion step. But I understand why you're asking for this: your existing code is close to doing what what you want.

Unfortunately, yeah, I don't think I want to go down the path of adding csv specific variants of serde features. Regretably, the serde integration in this library is easily its worst aspect. It is responsible for the vast majority of open bugs and open feature requests. And yet, it is undeniably super useful.

**Comment by chriskyndrid** [comment]
There is a corresponding JSON exporter already in play, which works great. That said, the System is a large ERP system that is being written in Rust on the backend, and many within its target audience desire the ability to export most elements of most screens into CSV format for various undefined uses. The use case for using the data in the json::Value columns is relatively low inasmuch as the user will really be impacted by not having them available in CSV format. Hence, exporting them, isn't super important, which is where I started. 

That said, there is already a fair amount of repetitious functionality that is derived from various macros and interrogating the data type in the macro and binding some additional logic to handle a conversion should be fairly straightforward, and I think the simplest after reviewing Serde's documentation further. 

Anyway, thanks again for the pointers and feedback. I still do think it could be useful to have a flag to allow skipping a given map, but also totally understand your perspective on it.
