### ISSUE TITLE
use serde

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/rust-csv#29]
I should start using `serde` for the automatic serialization component of this crate.

I don't think this means removing support for `rustc-serialize` just yet though.

**Comment by alexreg** [comment]
I agree, this is a good way to go. I've been told by some of the Rust developers that `rustc-serialize` doesn't have much of a future anyway, and `serde` is the best option for now. It's worth maintaining support for both, for the time being, however.

**Comment by BurntSushi** [comment]
`rustc-serialize` is still unfortunately more convenient to use. I'm not particularly keen on the maintenance burden of both at the moment, but would probably accept a PR at this point.

**Comment by alexreg** [comment]
More convenient in what way? Serde has matured quite a lot. It does everything rustc-serialize does plus a godo deal more.

**Comment by BurntSushi** [comment]
> It does everything rustc-serialize

That's not true. It doesn't support simple automatic derived implementations for types. It can do it using `build.rs` and code generations, but that has its own associated pitfalls.

**Comment by alexreg** [comment]
Nah, it has a plugin which does it just fine. Moving forwards they’ll be stabilised in Rust.

**Comment by BurntSushi** [comment]
> Nah, it has a plugin which does it just fine.

Plugins only work on Rust nightly.

**Comment by alexreg** [comment]
Hence why I said “they’ll be stabilised soon”. :)

**Comment by BurntSushi** [comment]
Hence why I said `rustc-serialize` is still more convenient to use. :-)

I'm well aware that serde is the future.

**Comment by alexreg** [comment]
Okay… rustc-serialize will be discontinued pretty much when this happens, as far as I understand.

**Comment by BurntSushi** [comment]
Most likely, yes.

**Comment by alexreg** [comment]
Okay. I’ll try to create a pull request, as it looks like serde support will be very useful for me.

**Comment by adwhit** [comment]
I have a serde fork which is getting close to mergable. Would appreciate comments prior to pull request:
https://github.com/adwhit/rust-csv/tree/serde/src

At the moment, the main tests are passing but some of the doctests (and all of the examples) are failing. Compile with `cargo test --features "merde"`

I'm not too sure how best to restructure the src folder. Probably best to have seperate `rustc_serialize` and `serde` folders a la https://github.com/TyOverby/bincode

**Comment by adwhit** [comment]
Only the doctests are failing now, at the moment it is not obvious to me how best to fix them without making the docs less readable.
The implementation abstracts over the serialization crate so that the user need only specify:
```csv = "*"```
for rustc-serialize and
```csv = {version = "*", features = ["serde"], default-features = false }```
for serde.

At the moment the benchmarks for serde are slightly slower which is a bit disappointing (yes, my laptop is incredibly slow)
```
➜  rust-csv git:(serde) cargo bench                                           

running 4 tests
test byte_records    ... bench:  28,097,780 ns/iter (+/- 278,721) = 48 MB/s
test decoded_records ... bench:  40,271,658 ns/iter (+/- 801,151) = 33 MB/s
test raw_records     ... bench:  18,208,329 ns/iter (+/- 138,020) = 74 MB/s
test string_records  ... bench:  31,426,010 ns/iter (+/- 598,485) = 43 MB/s

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured

➜  rust-csv git:(serde) cargo bench --features "serde" --no-default-features 

running 4 tests
test byte_records    ... bench:  28,203,438 ns/iter (+/- 355,633) = 48 MB/s
test decoded_records ... bench:  43,999,225 ns/iter (+/- 201,991) = 31 MB/s
test raw_records     ... bench:  18,190,173 ns/iter (+/- 111,631) = 75 MB/s
test string_records  ... bench:  31,521,580 ns/iter (+/- 113,910) = 43 MB/s

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured
```

**Comment by softprops** [comment]
+1

**Comment by donhcd** [comment]
@adwhit how's your fork doing?

**Comment by adwhit** [comment]
@donhcd There's a pull request for it; #43 . But it may have bitrotted since serde moved to 0.8 with breaking changes.

**Comment by syepes** [comment]
+1

**Comment by softprops** [comment]
status update on this?

**Comment by BurntSushi** [comment]
Nope.

**Comment by drusellers** [comment]
Now that 1.15 has shipped, does it make more sense to support Serde now?

**Comment by alexreg** [comment]
I hope so! :)

**Comment by coder543** [comment]
rustc-serialize is [now deprecated.](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485)

**Comment by BurntSushi** [comment]
I have a ground up rewrite in progress. It's actually mostly done. The remaining bits are to move to serde 1.0 and write docs... Lots of them. Rewrite is here: https://github.com/BurntSushi/rust-csv/tree/rewrite --- The goal is to reach 1.0. The rewrite, I think, fixes almost all outstanding bugs/feature requests.

**Comment by alexreg** [comment]
Nice work on the rewrite, @BurntSushi!
