### ISSUE TITLE
Writer does not support serialization of structs using serde flatten

### ISSUE THREAD

**Issue by cwlittle** [BurntSushi/rust-csv#305]
#### What version of the `csv` crate are you using?
1.2.1

#### Briefly describe the question, bug or feature request.
`csv::Writer` does not support serialization of structs using serde flatten.

#### Include a complete program demonstrating a problem.
```rust
use csv::{Reader, Writer};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Clone, Debug, Deserialize, Serialize)]
struct Foo {
    foo: u8,
}

#[derive(Debug, Default, Deserialize, Serialize)]
struct Bar {
    bar: u8,
}

#[derive(Debug, Deserialize, Serialize)]
struct FooBar {
    #[serde(flatten)]
    foo: Foo,
    #[serde(flatten)]
    bar: Bar,
}

fn main() {
    let mut reader = Reader::from_path(PathBuf::from("foo.csv")).unwrap();
    let records = reader
        .deserialize()
        .map(|result| result.unwrap())
        .collect::<Vec<Foo>>();

    let mut writer = Writer::from_path("foobar.csv").unwrap();
    records.iter().for_each(|record| {
        writer
            .serialize(FooBar {
                foo: record.to_owned(),
                bar: Bar::default(),
            })
            .unwrap();
    });
}
```
#### What is the observed behavior of the code above?

Error(Serialize("serializing maps is not supported, if you have a use case, please file an issue at https://github.com/BurntSushi/rust-csv"))

#### What is the expected or desired behavior of the code above?

I'm expecting, in this case, to have the writer output a csv with columns from the bar struct added.

**Comment by BurntSushi** [comment]
There have been many issues reported about this.
