### ISSUE TITLE
csv_reader.records() doesn't return a new iterator

### ISSUE THREAD

**Issue by f1am3d** [BurntSushi/rust-csv#309]
There are actually two joint bugs:
1. `csv_reader.records()` doesn't return a new iterator
2. `.records().count()` is not a pure function, because it consumes the iterator and it's not possible to use it twice

```rs
use std::fs::File;
use std::io::BufReader;
use csv::Reader;

fn count_records(file_path: &str) -> Result<usize, csv::Error> {
    let file = File::open(file_path)?;
    let reader = BufReader::new(file);
    let mut csv_reader = Reader::from_reader(reader);
    let count = csv_reader.records().count();
    
    println!("records count: {:?}", count); // records count: 100

    let count2 = csv_reader.records().count();

    println!("records count: {:?}", count2); // records count: 0
    
    Ok(count)
}
```

**Comment by BurntSushi** [comment]
This is correct behavior.

**Comment by f1am3d** [comment]
> This is correct behavior.

In which way it is?

**Comment by BurntSushi** [comment]
Your issue report doesn't really make it clear what specific thing you find unexpected. You don't even list the output you expect. So I don't really know how to answer that other than to say that code you've provided behaves as I would expect it to in every observable way that I can see.

**Comment by BurntSushi** [comment]
Maybe the thing you're missing is that a `csv::Reader` is a consumable resource, just like an `std::io::Read`. It is built on top of a `std::io::Read`, so it _necessarily_ assumes the same consumable behavior.

**Comment by BurntSushi** [comment]
So if you want to read all of the records again, then you need to create a new reader, or else provide something with a `std::io::Seek` impl and use [`csv::Reader::seek`](https://docs.rs/csv/latest/csv/struct.Reader.html#method.seek).
