### ISSUE TITLE
Reader::next_str internally takes a mutable borrow

### ISSUE THREAD

**Issue by marcusklaas** [BurntSushi/rust-csv#31]
This has basically been described in the comments already:
```
pub fn next_str(&mut self) -> NextField<str> {
        // This really grates me. Once we call `next_bytes`, we initiate a
        // *mutable* borrow of `self` that doesn't stop until the return value
        // goes out of scope. Since we have to return that value, it will never
        // go out of scope in this function.
        //
        // Therefore, we can't get access to any state information after
        // calling `next_bytes`. But we might need it to report an error.
        //
        // One possible way around this is to use interior mutability...
```
Would it be hard/tricky/nasty to fix this using interior mutability? Also, what's the best workaround for this in the mean while? Obviously one could clone, but that needlessly kills performance. Does a transmute also work?

edit: transmute works

**Comment by BurntSushi** [comment]
Cloning, interior mutability and (especially) transmutes are hammers. Unless we can come up with a clear argument for why they are necessary, then I'd like to avoid them. Of those three, only `transmute` would incur no extra overhead.

I can't remember exactly why I wrote that comment so angrily. What use cases is it preventing?

**Comment by marcusklaas** [comment]
Representing a record by
```rust
&[&str]
```
, for example. This may be needed as arguments for prepared statements.

**Comment by BurntSushi** [comment]
Ah. That is an unrelated problem and requires a completely different parsing architecture. Right now, the parser hangs on to exactly one field at a time. (So its memory usage is proportional to the size of the largest field rather than the size of the largest record.)

It would be an interesting exercise to see if that could be built on the existing parser without extraneous cloning. Probably not.

**Comment by marcusklaas** [comment]
Of course. Please excuse my ignorance.

**Comment by BurntSushi** [comment]
Not a problem. I'm glad you asked. See #32. :-)
