### ISSUE TITLE
Serve deserialization fails with flexible row size

### ISSUE THREAD

**Issue by PopFlamingo** [BurntSushi/rust-csv#314]
#### What version of the `csv` crate are you using?

1.2.1

#### Briefly describe the question, bug or feature request.

If a CSV document has rows with variating number of columns, serde deserialization fails even if the corresponding fields are `Option<T>`

#### Include a complete program demonstrating a problem.

```rs
#![allow(dead_code)]

use csv;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Record {
    a: String,
    b: String,
    c: String,
}

const SAMPLE_CSV: &'static str = "\
a,b,c
foo,bar\
";

fn main() {
    let csv_bytes = SAMPLE_CSV.as_bytes();
    let mut reader = csv::ReaderBuilder::new()
        .flexible(true)
        .from_reader(csv_bytes);
    let _: Record = reader.deserialize().next().unwrap().unwrap();
}
```

#### What is the observed behavior of the code above?

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Deserialize { pos: Some(Position { byte: 6, line: 2, record: 1 }), err: DeserializeError { field: None, kind: UnexpectedEndOfRow } })', src/main.rs:23:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

#### What is the expected or desired behavior of the code above?

The record should be deserialized with the properties corresponding to the missing  columns set to `Option::None`

**Comment by BurntSushi** [comment]
If you close an issue, it is good practice to post a comment saying why. And especially if you resolved your issue, to share it with others.

Otherwise, this is intended behavior. I would recommend enabling `flexible` on the reader builder.

**Comment by PopFlamingo** [comment]
@BurntSushi  The issue was due to the data I was parsing that missed a column. Is it expected for this to cause a decoding error even if the corresponding Rust struct field is optional? If not I can open a new issue.

**Comment by BurntSushi** [comment]
Yes. Because CSV rows with different lengths represent invalid CSV data. That's an error that occurs before Serde even touches it at all.

**Comment by PopFlamingo** [comment]
@BurntSushi I am using a reader with the `flexible` option enabled and it still fails, is this expected as well?

**Comment by PopFlamingo** [comment]
@BurntSushi I see, interesting! If I can I'll try to spend some time understanding what causes this to fail exactly in my case.
