### ISSUE TITLE
investigate alternative parsing architecture: keep entire record in memory at once

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/rust-csv#32]
Provoked by #31, the current parser hangs on to exactly one field while parsing. This means that in order to read an entire record into memory, you must at least clone each field returned by the core `next_bytes` method. This is the optimal strategy when your task can be formulated as a simple state machine over the data that doesn't need to look at the entire record at once. But if you do need to look at the whole record, you'll need to clone each field which can be costly.

Instead, we should investigate providing a parser that works like the current one, but hangs on to a record at a time. It would never emit a "field" event. Instead, it would only emit a "record" event that returns a borrowed slice into its internal buffer. This would be overwritten on the next parsing call.

This should actually improve performance for the "normal" cases like when one uses `records()`.

**Comment by tafia** [comment]
For information this is what is being done on [quick-csv](https://github.com/tafia/quick-csv/blob/master/src/lib.rs#L312-L369)
