### ISSUE TITLE
Feature: Manually add headers to new CSV, using proposed csv::Writer.push_header() function

### ISSUE THREAD

**Issue by pcgeek86** [BurntSushi/rust-csv#336]
#### What version of the `csv` crate are you using?

1.2.2

#### Briefly describe the question, bug or feature request.

While I was playing around with the `csv` crate, I found a potential gap in functionality. 

The `csv::StringRecord` type provides a `push_field()` function, which writes individual fields to a new CSV record. However, there is no way to manually write headers into a new CSV. Following the convention of having `push_field()` exposed on the `StringRecord` type, it would be convenient to add field headers by calling a (new) `push_header()` function on the Writer.

Maybe there's another way to manually add headers, that I'm not aware of?

#### Include a complete program demonstrating a problem.

```rust
fn main() -> Result<(), csv::Error> {
    let mut writer = csv::WriterBuilder::new().has_headers(true).from_path("target.csv")?;
  
    // ⚠️ These following two lines are what won't work (yet).
    writer.push_header("first_name");
    writer.push_header("last_name");  
  
    let mut new_record = csv::StringRecord::new();
    new_record.push_field("Trevor");
    new_record.push_field("Sullivan");
    
    writer.write_record(&new_record);
  
    Ok(())
  }
```

#### What is the observed behavior of the code above?

```
no method named `push_header` found for struct `Writer` in the current scope
method not found in `Writer<File>`
```

#### What is the expected or desired behavior of the code above?

Code should compile and run.
I propose that adding a `push_header(&str)` function to the `csv::Writer` would allow users of the `csv` crate to manually add new headers to a CSV.

**Suggestion**: Since the CSV could be flushed at any time, then adding headers _after_  records could result in malformed CSV data. If records have already been written to the CSV, without first adding headers, then an error should be thrown, **or** the entire CSV should be re-written to the target output (File, Stream, etc.).

**Comment by BurntSushi** [comment]
I don't understand the request. You can write a header record just like you would any other record. Why not try that?

```rust
fn main() -> Result<(), csv::Error> {
    let mut writer = csv::Writer::from_writer(std::io::stdout());

    let mut new_record = csv::StringRecord::new();
    new_record.push_field("first_name");
    new_record.push_field("last_name");
    writer.write_record(&new_record)?;
  
    let mut new_record = csv::StringRecord::new();
    new_record.push_field("Trevor");
    new_record.push_field("Sullivan");
    writer.write_record(&new_record)?;
  
    Ok(())
}
```

**Comment by pcgeek86** [comment]
Oh duh. I was mentally separating the concept of a record and a header, without thinking about the fact that I could do what you just said. 😅
