### ISSUE TITLE
How to change floating point precision?

### ISSUE THREAD

**Issue by SuperFluffy** [BurntSushi/rust-csv#34]
How can I change the precision of floating point numbers written to the file? For example, I obtain the result `2.0000000002, 2.0000000002`, while it should be `2.000000000200, 2.000000000201`.

The code below shows the issue:

````rust
extern crate csv;

fn main() {
    let mut wtr = csv::Writer::from_memory();
    let a = 2.000000000200f64;
    let b = 2.000000000201f64;
    let result = wtr.encode((a,b));
    assert!(result.is_ok());
    let f = format!("{},{}\n", a, b);
    println!("{}", f);
    println!("{}", wtr.as_string());
    assert_eq!(wtr.as_string(), f);
// thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `"2.0000000002,2.0000000002\n"`, right: `"2.0000000002,2.000000000201\n"`)', src/main.rs:12
}
````

**Comment by BurntSushi** [comment]
You can't with the automatic encoder. It [is hard-coded](https://github.com/BurntSushi/rust-csv/blob/master/src/encoder.rs#L164). It would probably be possible to expose an option on the encoder to control precision, but I'm not inclined to add it.

If you absolutely must do it, then don't use the automatic encoder. Instead, convert your values to strings and [write them manually](https://github.com/BurntSushi/rust-csv/blob/master/src/writer.rs#L234).

**Comment by SuperFluffy** [comment]
I have a similar issue with with reading `f64`, but I am not sure if this is directly related to `rust-csv`. The MWE showing the difference is at the bottom. It converts this:

````
    "-0.46370425355221123,
    -0.4637042535433742,
    -0.4637042535345472,
    -0.46370425352571626,
    -0.46370425351688843,
    -0.4637042535080646,
    -0.4637042534992198,"
````

to that:

````
[(-0.4637042535522113,), (-0.4637042535433742,), (-0.46370425353454725,), (-0.46370425352571626,), (-0.46370425351688843,), (-0.4637042535080646,), (-0.4637042534992198,)]
````

As you can see, there is a slight discrepency at the end. I need this to be exact though. :-/ Any ideas where I can look to fix this?

````
extern crate csv;

fn main() {
    let data = "
    -0.46370425355221123,
    -0.4637042535433742,
    -0.4637042535345472,
    -0.46370425352571626,
    -0.46370425351688843,
    -0.4637042535080646,
    -0.4637042534992198,";

    type Row = (f64,);
    let mut rdr = csv::Reader::from_string(data).has_headers(false);
    let rows = rdr.decode().collect::<csv::Result<Vec<Row>>>().unwrap();
    println!("{:?}", rows);
}
````

**Comment by BurntSushi** [comment]
Needing "floating point to be exact" is usually an indicator that you are headed down a path full of pain. By design, floating point is **not** exact. If you need exact, then you need to go out and find a special data structure that does just that.

With that said, I don't see how this is an issue with `csv`. You're assuming that printing floating point numbers with `{:?}` does not truncate. Indeed, it does. Here's an example: http://is.gd/tKA7TJ

**Comment by SuperFluffy** [comment]
Thanks for the feedback and the example. I had a sense I was doing something silly (and that most likely csv was not the culprit here).

**Comment by BurntSushi** [comment]
Yup. Floating point is hard and complex.
