### ISSUE TITLE
Writing does not have examples and works unexpectedly

### ISSUE THREAD

**Issue by cgswords** [BurntSushi/rust-csv#37]
I've been attempting to use this package to treat a CSV file as an ad-hoc database, but writing has given me some trouble.

First, there isn't an example in `examples` about how to write things.

Second, after reading through the code (which actually has a number of nice examples in the comments), I was surprised to read the following comment:

    impl Writer<fs::File> {
        /// Creates a new `Writer` that writes CSV data to the file path given.
        ///
        /// The file is created if it does not already exist and is truncated
        /// otherwise.
        pub fn from_file<P: AsRef<Path>>(path: P) -> Result<Writer<fs::File>> {
            Ok(Writer::from_writer(try!(fs::File::create(path))))
        }
    }

Given this, it seems like the only "easy" way to deal with a CSV file as a read/write object is to open the file myself and use another writer implementation to avoid nuking the file. It would be really nice if the writer implementation handled this for me.

**Comment by BurntSushi** [comment]
OK, so first and foremost, yes, there should be an example in the `examples` directory. With that said, the examples you saw "in the code" are actually published in the [API documentation](http://burntsushi.net/rustdoc/csv/struct.Writer.html).

Secondly, could you explain what is unexpected about the behavior? If `from_file` is doing what its documentation states, then that seems like it is behaving as expected.

With that said, it may not fit your use case. If so, that's OK, you can just use the `from_writer` constructor: http://burntsushi.net/rustdoc/csv/struct.Writer.html#method.from_writer In that case, there is no awareness of anything like a "file," so no truncation happens. I'm not sure exactly why this is inconvenient for you. It should be as simple as passing a file handle to `from_writer`.

I note that `from_file` is what you want 99% of the time.

**Comment by cgswords** [comment]
By unexpected, I mean the default truncation behavior provided by `std::fs::File::create` and mirrored here doesn't support the use case of 'csv file as a small i/o data store' (e.g., instead of a database or some such). I anticipated appending behavior (like [rustml](http://daniel-e.github.io/rustml/src/rustml/vectors.rs.html#231-234)). Even if that doesn't change, an error/warning if the file already exists might be nice.

That said, you're right that `from_writer`will do what I want. Thanks!
