### ISSUE TITLE
Can't decode plain enum

### ISSUE THREAD

**Issue by devyn** [BurntSushi/rust-csv#39]
Minimal test case:

``` rust
extern crate rustc_serialize;
extern crate csv;

#[derive(Debug, RustcDecodable)]
enum Code {
    One, Two, Three
}

fn main() {
    let mut rdr = csv::Reader::from_string("
a,b
One,1
Two,2
Three,3
Two,2
One,1");
    for x in rdr.decode() {
        let x: (Code, i32) = x.unwrap();
        println!("{:?}", x);
    }
}
```

Output:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Decode("Failed converting \'One\' from str.")', ../src/libcore/result.rs:688
```

Expected output:

```
(One, 1)
(Two, 2)
(Three, 3)
(Two, 2)
(One, 1)
```

rustc version: rustc 1.7.0 (a5d1e7a59 2016-02-29)

csv: 0.14.4  
rustc-serialize: 0.3.18

**Comment by BurntSushi** [comment]
Unfortunately, this is the way things are. I don't know how to support both zero parameter and one parameter enums. If you use `enum Code { One(String), ... }`, then that might work.

Perhaps serde will help fix this, so I'll leave it open.

**Comment by Eh2406** [comment]
I was just going to report this. Is there a workaround?

**Comment by BurntSushi** [comment]
@Eh2406 Well, yeah. Don't use `derive(RustcDecodable)`. Write your own implementation of `rustc_serialize::Decodable`. Here's an example that doesn't build an enum, but it should be straight-forward to adapt: https://github.com/BurntSushi/rust-csv/blob/master/examples/rational_numbers.rs#L19

**Comment by Eh2406** [comment]
Thanks! That fixed it. Is there some way we can make this not a silent error? This only came to my attention when a colleague noted that our work data was getting clobbered.

**Comment by BurntSushi** [comment]
@Eh2406 It is unfortunately pretty tricky to do. `rustc-serialize` doesn't allow much introspection on what's going on---it just kind of has to follow the interface of the `Decoder` trait. It's possible that Serde (the replacement to `rustc-serialize`) will be better, but I don't know if it will fix this specific case.

**Comment by purpleposeidon** [comment]
^

**Comment by BurntSushi** [comment]
The workaround is just fine. Sometimes you have to write your own decodable routine. That's just a part of serialization. I'm not sure what cfg has to do with this. 

Anyway, there's not much use in belaboring the point. I hope to move to serde soon.

**Comment by purpleposeidon** [comment]
I was pointing at https://github.com/purpleposeidon/rust-csv/commit/a999d9f0d022133e14f897747be01be46c0db6f7

**Comment by BurntSushi** [comment]
@purpleposeidon Oh, I missed that. I don't always use github.com to read/respond to comments. But ya, I'm definitely not doing that. I avoid features unless they're absolutely required.
