### ISSUE TITLE
Support for line comments?

### ISSUE THREAD

**Issue by jdiggans-twist** [BurntSushi/rust-csv#46]
Yes, CSV is a terrible format and no, there is no official way to denote comments in CSV files but it is terribly common to do so. Having another chained method to denote a line prefix that should cause a line to be skipped would be valuable, e.g.

```
csv::Reader::from_string(my_csv_string).has_headers(false).delimiter(b'\t').comment_char('#')
```

I tried adding this myself and submitting a PR but my rust is nowhere near good enough for that kind of bravado.

**Comment by BurntSushi** [comment]
Do other CSV libraries support this?

**Comment by jdiggans-twist** [comment]
Python pandas does (see 'comment' parameter):
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by BurntSushi** [comment]
Are there others?

Honestly, I'm not outright opposed to this, but I might be hesitant to do so if it impacts parsing speed.

**Comment by jdiggans-twist** [comment]
R supports the same (see read.csv variant):
https://stat.ethz.ch/R-manual/R-devel/library/utils/html/read.table.html

As does node.js:
http://csv.adaltas.com/parse/

Neither of these examples is famous for speed (although pandas is still quite fast; the parse happens in C) but this use pattern is very common in 'data science'-y applications in general and in bioinformatics in particular. 

See:

- http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40
- http://pythonforbiologists.com/index.php/manipulating-blast-output-with-command-line-tools/

for two very common CSV/TSV formats that contain #-delimited comments in *all* output from widely-used tooling.

If the comment char defaults to None, then the speed hit would come only from checking at run time whether comment was non-None which (hopefully) wouldn't cost much?

I could pre-parse the file and remove #-containing lines (akin to what is suggested by http://stackoverflow.com/a/30791678) but this would require two passes through most of the file instead of just one.

rust-bio (e.g. https://github.com/rust-bio/rust-bio/blob/master/src/io/bed.rs) uses rust-csv to parse e.g. BED files; the formal description of this format (e.g. https://genome.ucsc.edu/FAQ/FAQformat.html#format1) doesn't specify that comment lines are allowed but *in practice* comment lines are extremely common (meaning they would break the rust-bio parser due to rust-csv trying to interpret comment lines as data rows).

**Comment by gz** [comment]
I ended up with a dirty workaround for this that looks basially like this:

```rust
    for record in rdr.decode() {
        if record.is_ok() {
           // unwrap and go...
        }
        else {
            match record.unwrap_err() {
                csv::Error::Decode(s) => if !s.starts_with("Failed converting '#") { panic!("Can't decode line {}.", s) },
                e => panic!("Unrecoverable error {} while decoding.", e)
            };
        }
    }
```

It's a bit problematic as it has to rely on the specifc format of s in the Decode(s) error that is returned. Ideally, this error could return a more machine readable format Decode(line_nr, line, error)? But I guess that would be better reported as another issue.
