### ISSUE TITLE
Support for string delimiter?

### ISSUE THREAD

**Issue by loggerhead** [BurntSushi/rust-csv#47]
For example, I have some data with below format:

```rust
let data = "
sticker||mortals||7
bribed||personae||7
wobbling||poncing||4
interposed||emmett||9
chocolate||refile||7";
```

Everything is same as normal CSV data except the delimiter is `||` not `,`

**Comment by BurntSushi** [comment]
What happens when a field needs to contain `||`?

**Comment by loggerhead** [comment]
@BurntSushi I have to add two unused fields to fit the format.

```rust
#[derive(RustcDecodable)]
struct R {
    uid: u64,
    _1: Option<bool>,
    name: String,
    _2: Option<bool>,
    avatar_url: String,
}

fn main() {
    let data = "
sticker||mortals||7
bribed||personae||7
wobbling||poncing||4
interposed||emmett||9
chocolate||refile||7";

    let mut rdr = csv::Reader::from_string(data)
        .has_headers(false)
        .delimiter(b'|');

    let mut records: Vec<R> = Vec::new();
    for record in rdr.decode() {
        let r: R = record.unwrap();
        records.push(r);
    }
}
```

But what I want is something like:

```rust
    let mut rdr = csv::Reader::from_string(data)
        .has_headers(false)
        .delimiter("||"); // Use a str as delimiter rather than a char.
```

**Comment by BurntSushi** [comment]
No, I'm asking, what happens if your *data* needs to contain `||`? e.g., What if I want to encode `a||b` as a single field in a CSV row? How is `||` escaped? Is it doubled up? `||||`? Or slash escaped? `\|\|`? Something else?

**Comment by BurntSushi** [comment]
Do other CSV libraries support arbitrary length delimiters? If so, can you point them out to me? Python doesn't seem to support it:

```
>>> list(csv.reader(StringIO('a||b||c\nx||y||z'), delimiter='|'))
[['a', '', 'b', '', 'c'], ['x', '', 'y', '', 'z']]
>>> list(csv.reader(StringIO('a||b||c\nx||y||z'), delimiter='||'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    list(csv.reader(StringIO('a||b||c\nx||y||z'), delimiter='||'))
TypeError: "delimiter" must be an 1-character string
```

It frankly seems out of scope to me... And if the workaround you gave works for you, that actually seems like a pretty low price to pay for something so niche.

**Comment by loggerhead** [comment]
Don't bother, it seems other CSV libraries also only support 1-char delimiter, and the workaround works for me.
