### ISSUE TITLE
Is it possible to skip (n) first lines of the CSV?

### ISSUE THREAD

**Issue by iamsebastian** [BurntSushi/rust-csv#50]
At our API it's possbile to upload CSVs. Some of them are generated / exported via excel. That files could contain some *"header/encoding-trash"* in the first rows. So is it possible to skip n-first-lines, like with the `.has_headers` option?

Thanks in advance.

**Comment by BurntSushi** [comment]
No, it's not possible. I'd recommend using standard utilities such as `head` if you need to always skip N lines.

If there's some particular type of widely used CSV format that `xsv` could learn how to read, I might be open to that.

**Comment by iamsebastian** [comment]
Thanks for your quick response, @BurntSushi . Now, the customer is in force to deliver the CSV well formated.
