### ISSUE TITLE
Request: csv::Writer::has_headers

### ISSUE THREAD

**Issue by alubbe** [BurntSushi/rust-csv#52]
When encoding structs, it would be very useful to tell the writer to write a header line before the other content, similar to how `csv::Reader`` has`has_headers```. Right now, I am adding it manually and thereby am duplicating the struct keys, which I fear will cause bugs when new fields are added later and someone forgets to update the header string.
What do you think about adding this?

**Comment by BurntSushi** [comment]
Can you propose an implementation path?

**Comment by alubbe** [comment]
First of all, thanks for the super fast reply.
I have no idea how `derive` works, so I can only guess. In the logic where you generate the encoder, I would hope you have access to the field names of the struct, in the order that they will written into the csv. If all that applies, I would concatenate them using the separator to form the header line.

As I am thinking about this, does the current implementation guarantee that the order the fields will always be the same, i.e., as written in the struct definition?

**Comment by BurntSushi** [comment]
It's not really about `derive`, but how the `Encoder` API is built from the `rustc-serialize` crate. There's no explicit way to access the members of a struct. Instead, encoding (and decoding) is implemented with a visitor-style pattern. In other words, an implementation path of "just get the field names and write them" isn't quite detailed enough.

> As I am thinking about this, does the current implementation guarantee that the order the fields will always be the same, i.e., as written in the struct definition?

This actually is an artifact of the `derive` implementation. I'm not sure that this is necessarily guaranteed, but I'd be surprised if it ever changed. One can guarantee order by implementing `Decodable`/`Encodable` directly.

I kind of suspect that while this feature would be nice, it may be hard to implement. Moreover, I'd like to not continue developing new features on top of `rustc-serialize` and instead do this with serde once it's ready to be used on Rust stable. (Perhaps serde makes this particular feature easier to implement, I'm not sure.)

**Comment by alubbe** [comment]
I see your point about waiting on serde. AFAIK, it does work on stable if you work with a custom build script; so I would hope that their API is pretty much done now.

**Comment by flosse** [comment]
> Moreover, I'd like to not continue developing new features on top of `rustc-serialize` and instead do this with serde

What's the reason for this?

**Comment by BurntSushi** [comment]
Because serde is the future of serialization for Rust. rustc-serialize was a stop gap measure.
