### ISSUE TITLE
Request: multiline records optional

### ISSUE THREAD

**Issue by workanator** [BurntSushi/rust-csv#54]
Hello,

could you make multiline records optional? I'm asking because the files I process sometimes contain broken records where a field has open quote but has not closing quote and because of that the parser continues to searching for the end of the field on the next text line in the file. That conforms to CSV standard I know but it could be awesome if you can make that behavior optional.

Changes I suggest are
1. Add the new function to `Reader`, e.g. `fn multiline(self, yes: bool) -> Reader<R>`
2. By default multiline is set to `true` and that is what the current framework do.
3. If multiline is set to `false` and the end of the field is not found in the current line `Reader` returns an error.

**Comment by BurntSushi** [comment]
@workanator Does this have precedent in other CSV parsers? What happens with Python's in particular?

Note that there may be performance implications here.

This crate does do its best to parse broken CSV (even if it isn't spec conforming), but there's a limit to what we can do.

**Comment by workanator** [comment]
@BurntSushi Sorry I do not work on Python. I migrate my CSV tool set from Perl to Rust. I used the module [Text::CSV_XS](http://search.cpan.org/search?query=text%3A%3Acsv_xs&mode=all) it does not have such option but it parsing behavior differs from your framework. If that is not possible it's ok. I will look for a workaround solution.

**Comment by BurntSushi** [comment]
@workanator I think it would be fine to experiment with a feature like this and see if it can be done reasonably simply (and without sacrificing performance), but I'm unlikely to do it soon.

(I'd like to revamp the API in this crate, but just haven't had the chance to do so.)

**Comment by workanator** [comment]
@BurntSushi I will try to add that feature. If I success I will create a PR for review. Thanks.

**Comment by BurntSushi** [comment]
This issue is inactive, and it's not clear to me that we should actually support this.

**Comment by ark-** [comment]
I'd be interested in this feature. For context as to why: Microsoft Excel exports multi line CSV files. I commonly use this to export data from excel conveniently and often find myself having to manually remove newlines found between double quotes `"` in order for Rust libraries to parse this. Obviously this is lossy in that if I ever wanted to put the data back into Excel then the newlines are lost. Not a big deal but just adding to the dialog.

**Comment by BurntSushi** [comment]
@ark- That doesn't seem like what's being advocated here. This issue is asking for the ability to parse invalid multi-line records, but putting `\n` inside of quotes in CSV to extend records over multiple lines is perfectly valid and is certainly supported by this crate. Could you please file a new bug with an **example** in which output from Excel does not parse as you expect? Please make sure to provide a complete program, the input, the expected output and the actual output.

**Comment by ark-** [comment]
@BurntSushi You're right, my issue was a non UTF-8 character which just so happened to be in the only field with a newline. The process I used to remove the newline must have replaced with compliant UTF-8 characters.

Red herring ;)
