### ISSUE TITLE
read from socket

### ISSUE THREAD

**Issue by Trolldemorted** [BurntSushi/rust-csv#58]
Let's say i have a source sending me csv formatted data via tcp. Is there a *nice* way to feed it into rust-csv (i.e. not by writing it into file and reading it again)?

**Comment by BurntSushi** [comment]
As long as you have something that implements `io::Read` (and you should), then you can just use [`Reader::from_reader`](https://docs.rs/csv/0.15.0/csv/struct.Reader.html#method.from_reader).

**Comment by Trolldemorted** [comment]
thanks! TcpStream implements `io::Read`, so reading from a socket is as simple as reading from a file:

```
let mut stream = TcpStream::connect("127.0.0.1:8000").unwrap();
let mut rdr = csv::Reader::from_reader(stream);
for record in rdr.decode() {
    let record: Record = record.unwrap();
    // do fancy stuff
}
```
