### ISSUE TITLE
Feature Request: Record parsing based on field names

### ISSUE THREAD

**Issue by Tyler-Hardin** [BurntSushi/rust-csv#62]
I deal with CSVs with tons of extra columns, which exist for good reason, mostly debugging, but which I don't need for the average case processing. It would be incredibly tedious and brittle to write a tuple or record which contains a field for every column for every CSV schema I work with. Would it be possible to use struct field names along with a header row to only extract columns that are fields of the struct? That is, given a CSV with header `A,B,C,D` and a struct as below

    struct Rec {
        u32 A,
        u32 B,
        i32 D
    }

would it be possible to use the macro system to only decode columns A, B, and D, and omit column C?

**Comment by BurntSushi** [comment]
@Tyler-Hardin This has come up before but I can't immediately find the issue for it. AFAIK, the current decoder can't do this, and in general, doing this will require additional costs to maintain a field name mapping.

It would be worthwhile to investigate this while moving over to serde, which is something I hope to do. I just don't know when.

**Comment by Tyler-Hardin** [comment]
So, I went ahead and tried this. I'm ~50% satisfied with the result. I had to abuse custom derive/traits to do it, but meh. Maybe you could steal my idea and do it better.

Performance wise, considering how I do an integer index calculation once, then it's just integer offsets into a Vec, I think the lookup cost is trivial. With a little more work, it might even be possible to use the field based version of your parser. The biggest problem for performance is going to be that I call `.collect` instead of returning an iterator.

https://github.com/Tyler-Hardin/easy-csv

**Comment by BurntSushi** [comment]
@Tyler-Hardin Awesome work! Thanks for putting that together. :-) Happy to be wrong about perf!

**Comment by Tyler-Hardin** [comment]
I figured out how to do this with an iterator interface, but not zero alloc. The zero alloc version would require a vecmap lookup on every field and an additional if ladder on every field that's in the record. I'm not sure, but I think a single allocation per row will be faster than the vecmap lookup and if-ladder. Are you open to including this in the library? I could write it up by next weekend or maybe the following, but I see you have a few old, outstanding pull requests, so I'd like to get your tentative opinion before putting in the work. Not a hard commitment, just tentative.

Currently, the usage looks like:

    #[derive(Debug,CSVParsable,PartialEq)]
    struct Record {
        a: u32,
        b: i32
    }
    let mut rdr = csv::Reader::from_file("./test_input/test.csv").unwrap();
    let iter = CSVIterator::<Record,_>::new(&mut rdr);
    let res : Vec<Record> = iter.collect();
    assert_eq!(res, vec![Record { a: 2, b: -3 }]);

**Comment by Tyler-Hardin** [comment]
It would look more natural as a method on csv::Reader, though. Though I'm not sure what to call it, since you've already used the name records().

**Comment by BurntSushi** [comment]
At a high level, yes, I'm interested, but I don't know when I'll get a chance to look at this. I'd really like to flesh out a full plan for moving off of `rustc-serialize` and switching to serde first, and providing this functionality should be part of that plan. My apologies, but I don't think I'll be able to keep up with your pace on this one. :-(

**Comment by Tyler-Hardin** [comment]
It only occurred to me after I posted the above, but you're absolutely right to hold out on this for a serde based implementation. The problem is that I'm using FromStr as a poor man's deserializer, which is not okay for a major crate like this. Serde should definitely be the basis for the conversion to and from strings.
