### ISSUE TITLE
Why bump instead of bump_eor in StartRecord state?

### ISSUE THREAD

**Issue by AriaFallah** [BurntSushi/rust-csv#64]
[Here](https://github.com/BurntSushi/rust-csv/blob/cfc1ff2b4ab2abdb49dfa6b16e1f9ef1ca9aea37/src/reader.rs#L645) You have

```rust
StartRecord => {
    if self.is_record_term(c) {
        self.bump();
    } else {
        self.state = StartField;
    }
}
```

but everywhere else that you have a `is_record_term` you do a `bump_eor`, which as far as I know is needed to skip `\n` in the special case of `\r\n`.

So what I'm wondering is there some reason you wouldn't want to skip the `\n`? Am I missing the point, or is this a bug?

**Comment by BurntSushi** [comment]
> but everywhere else that you have a is_record_term you do a bump_eor, which as far as I know is needed to skip \n in the special case of \r\n.

I think this particular behavior is used to skip otherwise empty lines. In particular, from the docs:

> Empty lines (that do not include other whitespace) are ignored by the parser.

...

> Am I missing the point, or is this a bug?

If you think it's a bug, I think the most useful thing is to write a regression test and convince ourselves that the current behavior is wrong.

**Comment by BurntSushi** [comment]
Note that I'm in the middle of rewriting portions of this crate. In particular, a DFA based CSV parser: https://github.com/BurntSushi/rust-csv/blob/rewrite/csv-core/src/reader.rs (There should be no changes in parse behavior, even though the FSM is tweaked a bit.)

**Comment by AriaFallah** [comment]
@BurntSushi I don't think it's a bug to be honest 😅. I'm just trying to understand your code, and I really appreciate the swift response. I think

> Empty lines (that do not include other whitespace) are ignored by the parser.

Addresses it for me.

> Note that I'm in the middle of rewriting portions of this crate

Haha well shucks. [The parser I'm working on right now and keep messaging you about on reddit](https://github.com/AriaFallah/csv-parser) is based on the current version.

**Comment by BurntSushi** [comment]
@AriaFallah Ah right! I didn't make the connection with reddit. :-)

I think it's a good idea to base it on the existing one. It's much much simpler. The DFA parser is a rat's nest. (The DFA parser includes a fully functioning NFA parser, which looks a lot like the one on master and in your C++ code.)
