### ISSUE TITLE
Line ending not in compliance with RFC 4180

### ISSUE THREAD

**Issue by jamespole** [BurntSushi/rust-csv#67]
The documentation for [csv::Writer][1] claims that it generates [RFC 4180][2] compliant files with the exception of emply single record fields.

The RFC suggests a definition for CSV which specifies CRLF line endings (i.e. `\r\n`). However I note the [default configuration][3] in csv::Writer is actually for the single byte `\n`.

Resolution of this issue can be either updating the documentation to note this additional devitation from the definition suggested in the RFC or changing the default to CRLF.

[1]: http://burntsushi.net/rustdoc/csv/struct.Writer.html
[2]: https://tools.ietf.org/html/rfc4180
[3]: https://github.com/BurntSushi/rust-csv/blob/b65cca3ccdca75425e36e8a6eb127152363d3bec/src/writer.rs#L108

**Comment by BurntSushi** [comment]
That's true. We should update the docs.

**Comment by jamespole** [comment]
Well done on the rewrite. The docs still seems ambigious to me. For instance:

[rust-csv/csv-core/src/writer.rs](https://github.com/BurntSushi/rust-csv/blob/6f24780f26a81336bc919e4e2b07cdcadb0c309d/csv-core/src/writer.rs#L69)
````
    /// The record terminator to use when writing CSV.
    ///
    /// A record terminator can be any single byte. The default is a special
    /// value, `Terminator::CRLF`, which uses `\r\n` as the record terminator.
    ///
    /// The default is `b'\n'`.
    pub fn terminator(&mut self, term: Terminator) -> &mut WriterBuilder {
        self.wtr.term = term;
        self
    }
````

**Comment by BurntSushi** [comment]
Yeah, I fixed it in `csv` but forgot about `csv-core`. Should be all set now in https://github.com/BurntSushi/rust-csv/commit/ec7c348bc53e68b3c26556f677697ec1e4d965bb
