### ISSUE TITLE
Tutorial example tutorial-read-serde-04.rs won't compile

### ISSUE THREAD

**Issue by RonTilby** [BurntSushi/rust-csv#73]
While working through the CSV tutorial at: http://blog.burntsushi.net/csv/
I get a compilation error trying to compile the "tutorial-read-serde-04.rs" example.

error: unknown crate type: `proc-macro`

I get the error on both rust nightly and rust stable.

```
PS C:\users\ron\projects\csvtutor> rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.17.0 (56124baa9 2017-04-24)

PS C:\users\ron\projects\csvtutor> cargo build --verbose
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names --crate-type bin --crate-type proc-macro
--crate-type rlib --target x86_64-pc-windows-msvc` (exit code: 101)
--- stderr
error: unknown crate type: `proc-macro`


PS C:\users\ron\projects\csvtutor>
```

Here's a copy of my Cargo.toml file:

```
[package]
name = "csvtutor"
version = "0.1.0"
authors = ["Ron Tilby <rontilby@aol.com>"]

[dependencies]
csv = "1.0.0-beta.1"
serde = "1"
serde_derive = "1"
```

**Comment by BurntSushi** [comment]
This error is almost assured a result of a toolchain problem. My guess is that you're either accidentally using an older version of Rust somehow (Rust 1.15 stable or newer is required) or you've somehow wound up with a mismatch between your version of Cargo and your version of Rust.

**Comment by RonTilby** [comment]
Despite Rustup having already installed the current nightly and stable (on multiple days), I had an old rustc.exe (1.13.0), and that is what "cargo build" was actually running.  I uninstalled the old version, followed by another rustup update and that fixed the problem.
> rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
