### ISSUE TITLE
UTF-8 byte order mark can cause incorrect parsing

### ISSUE THREAD

**Issue by red75prime** [BurntSushi/rust-csv#81]
I can't find a way to configure the parser to correctly process CSV file, which starts with UTF-8 byte order mark (0xEF, 0xBB, 0xBF) followed by comment character ('#' in this case).

Sample file [bom_csv.zip](https://github.com/BurntSushi/rust-csv/files/1104424/bom_csv.zip)

Priority is low, it is simple enough to strip BOM from parser's input.

**Comment by BurntSushi** [comment]
Indeed, this library doesn't detect the UTF-8 BOM, so you'll need to strip it yourself for now. However, this does seem like a sensible feature to add. It should probably be done in `csv-core`.
