### ISSUE TITLE
Example from docs fails to build

### ISSUE THREAD

**Issue by alfiedotwtf** [BurntSushi/rust-csv#85]
I found that copy/pasting right from the example documentation fails to build:

    error[E0599]: no method named `write_record` found for type `csv::Writer<std::io::Stdout>` in the current scope
      --> src/main.rs:12:9

    12 |     wtr.write_record(&["city", "region", "country", "population"])?;

Thanks

**Comment by BurntSushi** [comment]
@alfiedotwtf This issue doesn't contain enough information. What version of the `csv` crate are you using? That is, what does your `Cargo.toml` say? In order to use the examples, you need to be using the most recent version of the crate, which is `1.0.0-beta.4`.

**Comment by alfiedotwtf** [comment]
Ah! Apologies, my mistake - I used the version number from the crates.io page - 0.15.0.

**Comment by BurntSushi** [comment]
@alfiedotwtf Ah yeah, that's... unfortunate. My plan is to cut a 1.0 release before the end of the year to give folks time to give feedback on the beta release. So I guess we'll just have to deal with it until then! :-(
