### ISSUE TITLE
Could we get tail vectors of Vec<f64>

### ISSUE THREAD

**Issue by posix4e** [BurntSushi/rust-csv#86]
I noticed this works with Vec<i32> but how hard would it be to get it work with Vec<f64> I don't think they have derive Eq

https://github.com/BurntSushi/rust-csv/blob/6ca9dce06d57af696d9ddcc99cd85aa8f1dc66ff/src/reader.rs#L908

**Comment by BurntSushi** [comment]
I don't understand this feature request. What code have you tried to write? What happened? What did you expect to happen? What higher level problem are you trying to solve?

**Comment by BurntSushi** [comment]
This issue is inactive and not actionable. Closing.
