### ISSUE TITLE
Serializing fat enums fails - undifferentiable outcome

### ISSUE THREAD

**Issue by drahnr** [BurntSushi/rust-csv#90]
```
fn main() {
        #[derive(Debug, Clone, Serialize, Deserialize)]
        enum Bug {
            Alpha(u32),
            Beta(u32),
            Gamma
        };

        let mut v1 = csv::WriterBuilder::new().from_writer(vec![]).serialize(Bug::Alpha(5)).unwrap();
        let mut v2 = csv::WriterBuilder::new().from_writer(vec![]).serialize(Bug::Beta(5)).unwrap();
        let mut v3 = csv::WriterBuilder::new().from_writer(vec![]).serialize(Bug::Gamma).unwrap();
        assert!(v1 != v2);
        assert!(v2 != v3);
        assert!(v3 != v1);
}
```

Fails at the first assert.

In the csv Alpha and Beta are both mapped to `5`.

**Comment by BurntSushi** [comment]
This seems like expected behavior to me, although perhaps the [docs could be clarified](https://docs.rs/csv/1.0.0-beta.4/csv/struct.Writer.html#method.serialize).

Could you perhaps say what behavior you expect to see happen? In particular, what should the CSV data look like?

**Comment by drahnr** [comment]
Well, it is unparseable. The Deserializer has no chance in recreating the original data structure. The information is just lost.
 Instead of just storing the enum enclosed value, it should also store the enum name. `Bug::Gamma` is serialized as `Gamma`, as such I would have expected `$name$delimiter$value` (where `$delimiter` is something other then the onfigured delimiter) or - as an alternative, convert it to tuples `($name, $value)` or even stick with the enum structure`$name($value)`

**Comment by BurntSushi** [comment]
Yeah, like I said, this is working as expected. You can't roundtrip enums in general. As you suggest, round tripping requires adding secondary structure to the CSV format. That would be nice if CSV were commonly used that way, but CSV isn't typically used to represent arbitrary data.

Instead of chasing general principles here, I would be much more receptive to use cases. My feeling is that the existing behavior is more useful.

**Comment by drahnr** [comment]
You are right, I missed that spot

Use case:
My use case is logging of `objects` / rust structs and later on serializing them again. CSV is used so it is easily interchangeable between people which will only be interested in a subset of the data.

**Comment by BurntSushi** [comment]
Yeah, I don't think CSV is the right format for that unless you add your
own translation layer that converts everything to tabular data. There are
plenty of data types that won't work at all, like enums with variants that
contain more than one field, most types of nested sequences and things like
nested maps too.

If you need to serialize arbitrary objects, then JSON seems like a much
better choice. If you want each log entry to be individually deserialized,
then use the "JSON lines" format.

**Comment by drahnr** [comment]
Fair enough.
