### ISSUE TITLE
cannot perform any action on csv with delimiter ';'

### ISSUE THREAD

**Issue by eleijonmarck** [BurntSushi/rust-csv#92]
printed_sign;link_no;event;seqno;descno_i;step_date;step_time;sign;uuid;state
;293676;54283;1;304497;15977;751; ;;
;257290;228425;1;268111;15865;407; ;;
;257295;228426;1;268116;15865;409; ;;
;313821;290549;1;324642;16043;742; ;;
;305663;54625;1;316484;16014;1102; ;;
;242342;53043;1;253163;15814;753; ;;
;99303;242876;1;110124;15325;611; ;;
;312465;102853;1;323286;16038;711; ;;
;312656;102859;1;323477;16039;784; ;;

Could you show a command that show the headers for this file

**Comment by BurntSushi** [comment]
@eleijonmarck I don't understand this bug report. Could you please provide a reproducible example, and describe the expected output versus the actual output?

**Comment by eleijonmarck** [comment]
Sorry for the unclear question

I have a csv of
printed_sign;link_no;event;seqno;descno_i;step_date;step_time;sign;uuid;state
;293676;54283;1;304497;15977;751; ;;

i would like to use xsv to have an option with:
xsv headers -delimiter ';' step_file.csv
printed_sign link_no   event   seqno descno_i step_date step_time sign uuid state
                      293676 54283 1          304497  15977        751

**Comment by BurntSushi** [comment]
That is not a reproducible example, and unfortunately, your question is still as unclear to me as it ever was. **Please consider spending more time making your problem understandable to other**. You're reporting this bug on `rust-csv`. If there is a problem with `xsv`, then please report it on the `xsv` issue tracker.

Please provide a *small compilable Rust program* that shows what you've tried, the actual output and the output you expect.

**Comment by BurntSushi** [comment]
This issue is inactive and isn't actionable.
